### ISSUE TITLE
[Bug] 使用docker部署, 并添加域名后, AI的输出打字效果消失

### ISSUE THREAD

**Issue by lainbo** [lobehub/lobe-chat#1204]
### 💻 系统环境

Debian12

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

我使用docker部署本项目在服务器, 当我和AI对话后, 他不再是一个字一个字的输出, 而是在等待一段时间后, 一次性输出所有文字。
已知触发条件是通过域名访问就会有问题, ip+端口访问则没有这个bug

https://github.com/lobehub/lobe-chat/assets/46062895/131fd939-0aa4-4323-a344-22e5cf9e36d9

### 🚦 期望结果

期待能够有打字输出的效果

### 📷 复现步骤

我使用docker-compose进行部署
```yml
version: '3.8'
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: "lobe-chat"
    ports:
      - "1401:3210"
    environment:
      - OPENAI_API_KEY=sk-xxxxx
      - ACCESS_CODE=example19
    restart: unless-stopped
```

或是使用docker命令部署
```sh
docker run -d -p 3210:3210 \
  -e OPENAI_API_KEY=sk-xxxxx \
  -e ACCESS_CODE=example19 \
  --name lobe-chat \
  lobehub/lobe-chat
```

部署后反向代理使用域名访问, 打字效果消失

### 📝 补充信息

目前测试出
- ip+端口, 打字效果还在
- http域名, 打字效果消失
- https域名, 打字效果消失
