### ISSUE TITLE
[Bug] v0.123.0到v0.124.2的版本,环境变量USE_AZURE_OPENAI=1无效,用户需要手动在设置中启用Azure OpenAI才能正常使用

### ISSUE THREAD

**Issue by fooooxxxx** [lobehub/lobe-chat#1260]
### 💻 系统环境

Linux

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

服务端环境变量配置了Azure的相关配置，用户打开页面后提示需要OpenAI Key.
用户在设置中勾选使用`Azure OpenAI`后不再需要OpenAI Key

这和预期不符

### 🚦 期望结果

服务端环境变量配置`USE_AZURE_OPENAI=1`和Azure相关配置后，用户打开页面后不需要去设置中勾选 `Azure OpenAI`和填入OpenAI Key即可使用

### 📷 复现步骤

使用0.123.0以及最新的0.124.2能复现该问题，在0.122.9版本下没有发现该问题

1. 在开发环境根目录下创建`.env.local` 输入azure openai相关配置
```env
AZURE_API_KEY=2********************
OPENAI_PROXY_URL=https://************.openai.azure.com/
USE_AZURE_OPENAI=1
AZURE_API_VERSION=2023-08-01-preview
```
2. 使用 `bun run dev`
3. 打开聊天页面，尝试聊天。会出现提示需要输入OpenAI Key
4. 在`设置`-`语言模型`勾选Azure OpenAI选项
5. 打开聊天页面，尝试聊天，不再出现提示需要输入OpenAI Key，且可以正常使用

### 📝 补充信息

0.122.9中没有发现该问题，猜测可能是0.123.0某些改动导致了该问题的出现

个人非前端，能力有限，读了会儿源码还是一筹莫展，希望开源贡献者帮忙看看这个bug。在此特别感谢

**Comment by xaya1001** [comment]
我第一次部署，好像还是遇到了这个问题，环境变量设置没用，需要到设置里面再填一遍，
版本是最新的0.129.6。
用的是docker compose文件，用了traefik反代，文件内容：
```
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    ports:
      - '3210:3210'
    environment:
      - USE_AZURE_OPENAI=1
      - OPENAI_PROXY_URL=https://*****.openai.azure.com
      - AZURE_API_KEY=*******
      - AZURE_API_VERSION=2024-02-15-preview
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.lobe-chat.entryPoints=websecure'
      - 'traefik.http.routers.lobe-chat.rule=Host(`******`)'
      - 'traefik.http.routers.lobe-chat.service=lobe-chat'
      - 'traefik.http.services.lobe-chat.loadbalancer.server.port=3210'
      - 'traefik.http.routers.lobe-chat.middlewares=authelia@file'
    networks:
      - traefik
networks:
  traefik:
    external: true
```
