### ISSUE TITLE
[Bug] 每次打开lobe-chat的话都需要自己重新刷新模型列表，才能使用其他模型

### ISSUE THREAD

**Issue by Yanyutin753** [lobehub/lobe-chat#2031]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

## 我没有设置`OPENAI_MODEL_LIST`环境变量，而是直接获取模型
![image](https://github.com/lobehub/lobe-chat/assets/132346501/bfc1da55-c61c-4db5-96fd-ac5b114c58b2)

### 🚦 期望结果

1. 可以把第一次请求得到的模型结果缓存起来，之后就可以直接使用
2. 之后要是在进行请求模型的时候，在更换缓存数据
3. 这样方便很多

### 📷 复现步骤

1. 请求模型，之后能正常使用
2. 关闭lobe-chat，之后再打开，还得请求模型，才能正常使用一些模型

### 📝 补充信息

感谢lobe-chat

**Comment by arvinxx** [comment]
你更新到最新版本了吗？我应该是有缓存的

**Comment by Menghuan1918** [comment]
同样的问题，使用的docker-compose部署，但是每次网页刷新之后有一些模型都识别不了，例如claude-3-sonnet-20240229

![图片](https://github.com/lobehub/lobe-chat/assets/122662527/2591b024-d55a-418c-bff9-2531b1fb00e1)

但是点击获取模型列表之后就好了

![图片](https://github.com/lobehub/lobe-chat/assets/122662527/996e66c5-61ba-4c6a-b34d-4115f3163924)

在Chrome和Firefox都是这样，以下是我使用的docker-compose.yml

```yml
version: '3.8'
services:
  lobe-chat:
    image: lobehub/lobe-chat:latest
    container_name: lobe-chat
    restart: always
    ports:
      - '2000:3210'
```
