### ISSUE TITLE
[Bug] OLLAMA_MODEL_LIST 不生效

### ISSUE THREAD

**Issue by fgprodigal** [lobehub/lobe-chat#2063]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

OLLAMA_MODEL_LIST未直接生效，需要点击设置里的ollama-模型列表-重置才能显示配置的模型

### 🚦 期望结果

直接生效，不需要额外操作

### 📷 复现步骤

```yaml
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    environment:
      - ACCESS_CODE=yyyyyy
      - OLLAMA_PROXY_URL=http://xxxxxx:11434/v1
      - OLLAMA_MODEL_LIST=+yi,+yi:34b
      - OPENAI_MODEL_LIST=-gpt-4-turbo,-gpt-4-turbo-preview,-gpt-4-vision-preview
      - DEFAULT_AGENT_CONFIG=model=gpt-3.5-turbo;provider=openai
      - NEXTAUTH_SECRET=aaaaaaa
      - SSO_PROVIDERS=auth0
      - AUTH0_CLIENT_ID=zzzzzzz
      - AUTH0_CLIENT_SECRET=bbbbbbbb
      - AUTH0_ISSUER=https://ttttttt
      - NEXTAUTH_URL=http://ddddddd:3210/api/auth
      - OPENAI_API_KEY=sk-key
      - OPENAI_PROXY_URL=https://iiiiiii/v1
    ports:
      - '3210:3210'
```

docker compose up -d
