### ISSUE TITLE
[Request] 如何自定义字体？

### ISSUE THREAD

**Issue by sherlcok314159** [lobehub/lobe-chat#2401]
### 🥰 需求描述

可以有一些浏览器插件可以重新定义字体，请问具体是哪些 css 跟字体相关呢？希望可以自定义字体

### 🧐 解决方案

希望作者可以提供解决方案，谢谢

**Comment by Ruhi-Khan** [comment]
I have updated the README.md 
 Identify the CSS properties related to font customization
• Update the documentation with the information on how to customize fonts

**Comment by Ruhi-Khan** [comment]
actually I'm the beginner the task was assigned to me to do this so it will be kind of you if you can guide me through...

**Comment by arvinxx** [comment]
你需要自定义啥字体？是应用的还是对话的？

**Comment by sherlcok314159** [comment]
尽可能全部吧，麻烦你啦

**Comment by sxjeru** [comment]
简单粗暴的 CSS 替换全网页字体如下，可用于 Stylus 扩展。

``` css
body * {
  font-family: "fontName" !important ; 
}
```

**Comment by sherlcok314159** [comment]
是的，只能这样比较方便，还得加上边栏的字体

```css
    .css-cqoetk.ant-typography,
    body * {
      font-family: "YOUR FONT";
    }
```
