### ISSUE TITLE
[Request] 如何设置时区？

### ISSUE THREAD

**Issue by sherlcok314159** [lobehub/lobe-chat#2680]
### 🥰 Feature Description

如果能设置时区，会比较方便

### 🧐 Proposed Solution

比较方便的方法是用 `docker-compose.yml`的 `TZ` 来实现：

```
version: '3'
services:
    lobe-chat:
        image: lobehub/lobe-chat:latest
        container_name: lobe-chat
        environment:
            - TZ=Asia/Shanghai
        restart: unless-stopped
        ports:
            - "3210:3210"
 ```
