### ISSUE TITLE
[Bug] docker部署时next-auth不可用

### ISSUE THREAD

**Issue by xingpingcn** [lobehub/lobe-chat#2881]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

最新

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/117259690/f805b498-f425-4bfb-a2dc-f226ad0bbd6d)

![image](https://github.com/lobehub/lobe-chat/assets/117259690/5685087c-4485-402b-85a4-d88b464919ce)

```yml
version: '3.8'

services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - '127.0.0.1:10901:3210'
```

使用ngxin反代

```
server {
        server_name domain.com;
        listen 80;
        location /{
            proxy_pass http://127.0.0.1:10901;
        }
}
```

因为套了cf，所以，虽然监听的80端口，但是https是可用的
