### ISSUE TITLE
[Bug] "Error: @clerk/nextjs: Missing publishableKey." despite the correct ENVs being set 

### ISSUE THREAD

**Issue by Lukasz-pluszczewski** [lobehub/lobe-chat#3086]
### 📦 Environment

Docker

### 📌 Version

1.1.15

### 💻 Operating System

macOS, Ubuntu

### 🌐 Browser

Chrome, Safari, Other

### 🐛 Bug Description

I'm getting an error that the publishableKey is missing
```
Error: @clerk/nextjs: Missing publishableKey. You can get your key at https://dashboard.clerk.com/last-active?path=api-keys.
```

despite it being provided in an env variable. I've tripple checked if correct envs are set and the env's value is set correctly when I check in the running container (e.g. with a `echo "${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}"` command). 
It's the same when running the docker-compose locally on macOS or on the Ubuntu server when using portainer.

### 📷 Recurrence Steps

Just run docker compose like the one below.

### 📝 Additional Information

Docker-compose used to run the app

```
version: "3.7"

services:
  lobe:
    image: lobehub/lobe-chat
    environment:
      OPENAI_API_KEY: '${OPENAI_API_KEY}'
      FEATURE_FLAGS: 'webrtc_sync'
      DATABASE_URL: 'postgres://lobe:${POSTGRES_PASSWORD}@postgres:5432/lobechat'
      DATABASE_DRIVER: 'node'
      NEXT_PUBLIC_SERVICE_MODE: 'server'
      KEY_VAULTS_SECRET: '${KEY_VAULTS_SECRET}'
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: '${CLERK_PUBLISHABLE_KEY}'
      CLERK_SECRET_KEY: '${CLERK_SECRET_KEY}'
      CLERK_WEBHOOK_SECRET: '${CLERK_WEBHOOK_SECRET}'
      S3_BUCKET: 'lobechat'
      S3_ENDPOINT: '${S3_ENDPOINT}'
      S3_ACCESS_KEY_ID: '${S3_ACCESS_KEY_ID}'
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY}'
    ports:
      - 3210:3210
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: lobechat
      POSTGRES_USER: lobe
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - lobechat_data:/var/lib/postgresql/data

volumes:
  lobechat_data:
```
