### ISSUE TITLE
[Bug] Clerk integration is broken

### ISSUE THREAD

**Issue by waclawthedev** [lobehub/lobe-chat#3516]
### 📦 Environment

Docker

### 📌 Version

v1.11.8

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

After tying to visit http://localhost:3210/ I see Application error: `a client-side exception has occurred (see the browser console for more information).` In chrome console: 
```
layout-55d8206e8f530a3d.js:1 Uncaught (in promise) 
Error: Cannot find module './en-us.js'
    at layout-55d8206e8f530a3d.js:1:15536
    at async layout-55d8206e8f530a3d.js:1:33151
59128-57db5d32a47acd7f.js:1 
Error: @clerk/nextjs: Missing publishableKey. You can get your key at https://dashboard.clerk.com/last-active?path=api-keys.
    at Object.throwMissingPublishableKeyError (27631-6d4d762f9b5319cd.js:1:44405)
    at 27631-6d4d762f9b5319cd.js:1:37040
    at rE (03a983a9-e6edb4c715482cd6.js:1:40343)
    at iZ (03a983a9-e6edb4c715482cd6.js:1:117028)
    at ia (03a983a9-e6edb4c715482cd6.js:1:95164)
    at 03a983a9-e6edb4c715482cd6.js:1:94986
    at il (03a983a9-e6edb4c715482cd6.js:1:94993)
    at oJ (03a983a9-e6edb4c715482cd6.js:1:92349)
    at oZ (03a983a9-e6edb4c715482cd6.js:1:91768)
    at MessagePort.M (59128-57db5d32a47acd7f.js:1:92034)
03a983a9-e6edb4c715482cd6.js:1 Uncaught 
Error: Minified React error #423; visit https://react.dev/errors/423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at iZ (03a983a9-e6edb4c715482cd6.js:1:118351)
    at ia (03a983a9-e6edb4c715482cd6.js:1:95164)
    at 03a983a9-e6edb4c715482cd6.js:1:94986
    at il (03a983a9-e6edb4c715482cd6.js:1:94993)
    at oJ (03a983a9-e6edb4c715482cd6.js:1:92349)
    at oZ (03a983a9-e6edb4c715482cd6.js:1:91768)
    at MessagePort.M (59128-57db5d32a47acd7f.js:1:92034)
```

My docker compose config:
```
  chat:
    image: lobehub/lobe-chat:v1.11.8
    container_name: lobe-chat
    restart: always
    ports:
      - '3210:3210'
    environment:
      ACCESS_CODE: lobe66
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_live_***
      CLERK_SECRET_KEY: sk_live_***
```
