### ISSUE TITLE
[Request] 提供一个部署服务端数据库版的docker-compose.yml

### ISSUE THREAD

**Issue by 370738206** [lobehub/lobe-chat#3569]
### 🥰 需求描述

提供一个部署服务端数据库版的docker-compose.yml

### 🧐 解决方案

``` yml
version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: my-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data  
    networks:
      - pg

  lobe-chat-database:
    image: lobehub/lobe-chat-database
    container_name: lobe-chat-database
    environment:
      # 基础变量
      OPENAI_PROXY_URL: ''
      OPENAI_MODEL_LIST: ''
      OPENAI_API_KEY: ''
      # 网站域名
      APP_URL: ""	# 使用ip+端口形式
      # DB 必须的环境变量
      KEY_VAULTS_SECRET: "jgwsK28dspyVQoIf8/M3IIHl1h6LYYceSYNXeLpy6uk="
      DATABASE_URL: "postgres://postgres:mysecretpassword@my-postgres:5432/postgres"
      # 身份验证
      NEXT_AUTH_SECRET: ""
      NEXT_AUTH_SSO_PROVIDERS: ""
      NEXTAUTH_URL: ""
      AUTH0_CLIENT_ID: ""
      AUTH0_CLIENT_SECRET: ""
      AUTH0_ISSUER: ""
      # 存储
      S3_ACCESS_KEY_ID: ""
      S3_SECRET_ACCESS_KEY: ""
      S3_ENDPOINT: ""
      S3_BUCKET: ""
      NEXT_PUBLIC_S3_DOMAIN: ""
    ports:
      - "3210:3210"
    networks:
      - pg
    depends_on:
      - postgres


networks:
  pg:
    driver: bridge
```
