### ISSUE TITLE
[Bug] 对话后刷新网页，对话不会保留

### ISSUE THREAD

**Issue by BiFangKNT** [lobehub/lobe-chat#3864]
### 📦 部署环境

Docker

### 📌 软件版本

lobehub/lobe-chat-database:1.15.26

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

对话完刷新网页，或者单纯是切换一下对话，对话内容都会消失

对话：
![image](https://github.com/user-attachments/assets/1c2990e3-8238-4e52-b7bf-80eb679bc18d)
切换一下对话：
![image](https://github.com/user-attachments/assets/034b9362-7f25-42fb-a71d-47bcf2a35f9b)
![image](https://github.com/user-attachments/assets/2c749347-44d8-4036-8a64-36db3f15bf63)

各容器没有报错

docker-compose如下：
```
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '5454:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=lobe'
      - 'POSTGRES_PASSWORD=（占位符）'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - '19000:9000'
      - '19001:9001'
    volumes:
      - './s3_data:/data'
    environment:
      - 'MINIO_ROOT_USER=（占位符）'
      - 'MINIO_ROOT_PASSWORD=（占位符）'
      - 'MINIO_DOMAIN=minio.（占位符）'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=https://lobechat.（占位符）' # Your LobeChat's domain name.
    restart: always
    command: >
      server /data --address ":9000" --console-address ":9001"


  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-database
    ports:
      - '3210:3210'
    volumes:
      - '/volume1/docker/lobechat/resolv.conf:/etc/resolv.conf'
    depends_on:
      - postgresql
      - minio
#      - logto
    env_file:
      - .env
    restart: always

volumes:
  data:
    driver: local
  s3_data:
    driver: local
```

.env如下：
```
# 必填，LobeChat 域名，用于 tRPC 调用
# 请保证此域名在你的 NextAuth 鉴权服务提供商、S3 服务商的 CORS 白名单中
APP_URL=https://lobechat.（占位符）/

# Postgres 相关，也即 DB 必需的环境变量
# 必填，用于加密敏感信息的密钥，可以使用 openssl rand -base64 32 生成
KEY_VAULTS_SECRET=（占位符）
# 必填，Postgres 数据库连接字符串，用于连接到数据库
# 格式：postgresql://username:password@host:port/dbname，如果你的 pg 实例为 Docker 容器且位于同一 docker-compose 文件中，亦可使用容器名作为 host
DATABASE_URL=postgresql://postgres:（占位符）@192.168.5.8:5454/lobe

# NEXT_AUTH 相关，也即鉴权服务必需的环境变量
# 可以使用 auth0、Azure AD、GitHub、Authentik、Zitadel、Logto 等，如有其他接入诉求欢迎提 PR
# 目前支持的鉴权服务提供商请参考：https://lobehub.com/zh/docs/self-hosting/advanced/auth#next-auth
# 如果你有 ACCESS_CODE，请务必清空，我们以 NEXT_AUTH 作为唯一鉴权来源
# 必填，用于 NextAuth 的密钥，可以使用 openssl rand -base64 32 生成
NEXT_AUTH_SECRET=（占位符）
# 必填，指定鉴权服务提供商，这里以 Logto 为例
NEXT_AUTH_SSO_PROVIDERS=cloudflare-zero-trust
# 必填，NextAuth 的 URL，用于 NextAuth 的回调
NEXTAUTH_URL=https://lobechat.（占位符）/api/auth

# NextAuth 鉴权服务提供商部分，以 Logto 为例
# 其他鉴权服务提供商所需的环境变量，请参考：https://lobehub.com/zh/docs/self-hosting/environment-variables/auth

CLOUDFLARE_ZERO_TRUST_CLIENT_ID=（占位符）
CLOUDFLARE_ZERO_TRUST_CLIENT_SECRET=（占位符）
CLOUDFLARE_ZERO_TRUST_ISSUER=https://（占位符）.cloudflareaccess.com/cdn-cgi/access/sso/oidc/（占位符）


# 代理相关，如果你需要的话（比如你使用 GitHub 作为鉴权服务提供商）
# HTTP_PROXY=http://localhost:7890
# HTTPS_PROXY=http://localhost:7890

# S3 相关，也即非结构化数据（文件、图片等）存储必需的环境变量
# 这里以 MinIO 为例
# 必填，S3 的 Access Key ID，对于 MinIO 来说，直到在 MinIO UI 中手动创建之前都是无效的
S3_ACCESS_KEY_ID=（占位符）
# 必填，S3 的 Secret Access Key，对于 MinIO 来说，直到在 MinIO UI 中手动创建之前都是无效的
S3_SECRET_ACCESS_KEY=（占位符）
# 必填，S3 的 Endpoint，用于服务端/客户端连接到 S3 API
S3_ENDPOINT=https://minio.（占位符）
# 必填，S3 的 Bucket，直到在 MinIO UI 中手动创建之前都是无效的
S3_BUCKET=lobe
# 必填，S3 的 Public Domain，用于客户端通过公开连接访问非结构化数据
S3_PUBLIC_DOMAIN=https://minio.（占位符）
# 选填，S3 的 Enable Path Style
# 对于主流 S3 Cloud 服务商，一般填 0 即可；对于自部署的 MinIO，请填 1
# 请参考：https://lobehub.com/zh/docs/self-hosting/advanced/s3#s-3-enable-path-style
S3_ENABLE_PATH_STYLE=1

# 其他基础环境变量，视需求而定。注意不要有 ACCESS_CODE
# 请参考：https://lobehub.com/zh/docs/self-hosting/environment-variables/basic
# 请注意，对于服务端版本，其 API 必须支持嵌入（即 OpenAI text-embedding-3-small）模型，否则无法对上传文件进行处理，但你无需在 OPENAI_MODEL_LIST 中指定此模型
OPENAI_API_KEY=（占位符）
OPENAI_PROXY_URL=https://api.chatanywhere.tech/v1
DEEPSEEK_API_KEY=（占位符）
ZHIPU_API_KEY=（占位符）
# OPENAI_MODEL_LIST=...
```

### 📷 复现步骤

如上所述

### 🚦 期望结果

正常保留对话
