### ISSUE TITLE
[Bug] ollama 支持 vision的大模型（如minicpm-v）依然存在无法发送图片的情况

### ISSUE THREAD

**Issue by tyzero** [lobehub/lobe-chat#3999]
### 📦 Environment

Docker

### 📌 Version

v1.17.7

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

minicpm-v 默认配置下（点击重置配置），可以正常发送图片。

但是，经过 更新模型列表（**点击获取模型列表**）操作后，vision 配置似乎被覆盖删除，
![image](https://github.com/user-attachments/assets/c2da9d38-248e-4073-8a08-41a16eb7aeb3)

导致模型在UI界面里无法发送图片
![image](https://github.com/user-attachments/assets/e5f70f65-b55a-487e-a2a0-56f2f155671c)

**Comment by tyzero** [comment]
@Dosu 谢谢你AI侠，我看了下代码，parseModelString 似乎只针对 在服务端配置了Model List 的情况，才 能够正确解析 模型的附带能力（vision），如果没有配置 modle list，transformToChatModelCards  会使用默认模型配置，这个defaultChatModels应该有问题。我用的lobechat 是 其他人部署的，但ollama是我本地电脑的服务，我只是需要用到 lobechat 的UI，但却需要去后台配置它支持的能力，这很不合理。

**Comment by dkkb** [comment]
According to the official Lobechat documentation available at [ollama](https://lobehub.com/zh/docs/self-hosting/environment-variables/model-provider#ollama) and [model list](https://lobehub.com/zh/docs/self-hosting/advanced/model-list), it appears that Lobechat supports custom vision LLM models through environment variables. While it can fetch the model list, it doesn't specifically check whether the model supports vision.

To use a visual model in Docker Compose, you need to add the following environment variables. The same OLLAMA_MODEL_LIST configuration applies to the Dockerfile:

```
version: '3.8'

services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - '3210:3210'
    environment:
      ACCESS_CODE: xx
      OLLAMA_MODEL_LIST: llava:34b-v1.6-q4_K_M=llava 34b<128000:vision>
```
