### ISSUE TITLE
[Bug] [TRPCError]: UNAUTHORIZED - docker + auth0/github App + 腾讯 COS 

### ISSUE THREAD

**Issue by eachann1024** [lobehub/lobe-chat#4023]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

macOS, Ubuntu

### 🌐 Browser

Chrome, Other

### 🐛 Bug Description

| 基于 docker + postgres + lobechat 部署

![CleanShot 2024-09-19 at 17 27 00@2x](https://github.com/user-attachments/assets/4ecdbdf3-77aa-484d-b296-e2624a590e97)

一开始使用的是 github app ， 后来出现 `[TRPCError]: UNAUTHORIZED` 错误之后， 更换 auth0，跟着文档来配置，也是不行

---

I started using the github app, but after getting a `[TRPCError]: UNAUTHORIZED` error, I replaced auth0 and followed the docs, but it didn't work either.

![CleanShot 2024-09-19 at 17 28 05@2x](https://github.com/user-attachments/assets/288b24b2-ab1c-4ce6-b740-8a53813bccde)

```yaml
version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: Postgres
    restart: always
    ports:
      - '5432:5432' 
    volumes:
      - /postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin # 设置 Postgres 的用户名
      POSTGRES_PASSWORD: 123456 # 设置 Postgres 的密码
      POSTGRES_DB: lobechat # 设置默认数据库名称
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      - 'postgres'
      - '-c'
      - 'listen_addresses=*'

  # LobeChat 应用服务
  lobechat:
    image: lobehub/lobe-chat-database:latest
    container_name: LobeChatDB
    restart: always
    ports:
      - '3210:3210'
    depends_on:
      - postgres
    environment:
      APP_URL: 'https://chat.xxxx'
      DATABASE_URL: postgres://admin:123456@postgres/lobechat
      KEY_VAULTS_SECRET: 'xxx'
      # 腾讯 COS 配置
      # S3_ACCESS_KEY_ID: 'xxx'
      # S3_SECRET_ACCESS_KEY: 'xxx'
      # S3_BUCKET: 'xxx'
      # S3_REGION: 'ap-guangzhou'
      # S3_ENDPOINT: 'https://cos.ap-guangzhou.myqcloud.com'
      # S3_PUBLIC_DOMAIN: 'xxx'
      # Auth0配置
      NEXT_AUTH_SSO_PROVIDERS: 'auth0'
      AUTH_AUTH0_ID: 'xxx'
      AUTH_AUTH0_SECRET: 'xxx'
      AUTH_AUTH0_ISSUER: 'https://chat.xxxx/api/auth/callback/auth0'
      ACCESS_CODE: 'xxx'
    volumes:
      - /LobeChatDB/app/data:/app/data

# 定义内部网络（可选）
networks:
  default:
    driver: bridge

```

**Comment by eachann1024** [comment]
论坛找了好几次， 没看到合适的解决方案
I've searched the forums a few times, but haven't seen a suitable solution.

**Comment by SpeedupMaster** [comment]
`ACCESS_CODE: 'xxx'`
这个不需要了
`AUTH_AUTH0_ISSUER: 'https://chat.xxxx/api/auth/callback/auth0'`
还有这个ISSUER应该是Auth0 应用程序的 Domain

**Comment by Autumnor** [comment]
我是一开始Auth0，整了一天都不行😭 睡前换成github就可以了。

**Comment by eachann1024** [comment]
> `ACCESS_CODE: 'xxx'` 这个不需要了 `AUTH_AUTH0_ISSUER: 'https://chat.xxxx/api/auth/callback/auth0'` 还有这个ISSUER应该是Auth0 应用程序的 Domain

      NEXT_AUTH_SSO_PROVIDERS: 'auth0'
      AUTH_AUTH0_ID: 'BxH'
      AUTH_AUTH0_SECRET: 'b07'
      AUTH_AUTH0_ISSUER: 'dev-xxx.jp.auth0.com'
      
      改成了 domain 也是不生效
      
      错误还是这个问题
      
<img width="737" alt="image" src="https://github.com/user-attachments/assets/862d5be5-b5a4-43d4-a324-7e021acfa176">



目前的配置文件
```yaml
version: '3.8'

services:
  # Postgres 数据库服务，包含 PGVector 插件
  postgres:
    image: pgvector/pgvector:pg16
    container_name: Postgres
    restart: always
    ports:
      - '5432:5432' # 映射主机的5432端口到容器
    volumes:
      - Docker/postgres/data:/var/lib/postgresql/data # 持久化数据存储
    environment:
      POSTGRES_USER: admin # 设置 Postgres 的用户名
      POSTGRES_PASSWORD: 1234 # 设置 Postgres 的密码
      POSTGRES_DB: lobechat # 设置默认数据库名称
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      - 'postgres'
      - '-c'
      - 'listen_addresses=*'

  # LobeChat 应用服务
  lobechat:
    image: lobehub/lobe-chat-database:latest
    container_name: LobeChatDB
    restart: always
    ports:
      - '3210:3210'
    depends_on:
      - postgres
    environment:
      APP_URL: 'https://chat.xxx.site'
      DATABASE_URL: postgres://admin:1234@postgres/lobechat
      KEY_VAULTS_SECRET: 'xxx'
      # 腾讯 COS 配置
      S3_ACCESS_KEY_ID: 'xxxx'
      S3_SECRET_ACCESS_KEY: 'xxx'
      S3_BUCKET: 'lobechat-xx'
      S3_REGION: 'ap-guangzhou'
      S3_ENDPOINT: 'https://cos.ap-guangzhou.myqcloud.com'
      S3_PUBLIC_DOMAIN: 'https://lobechat-xx.ap-guangzhou.myqcloud.com'
      # Auth0配置
      NEXT_AUTH_SSO_PROVIDERS: 'auth0'
      AUTH_AUTH0_ID: 'xxx'
      AUTH_AUTH0_SECRET: 'xxx'
      AUTH_AUTH0_ISSUER: 'dev-xxx.jp.auth0.com'
    volumes:
      - Docker/LobeChatDB/app/data:/app/data

```
