### ISSUE TITLE
[Request] 是否可以提供一个casdoor生产部署的docker-compose的参考文件

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#4080]
### 🥰 需求描述

是否可以提供一个casdoor生产部署的docker-compose的参考文件

### 🧐 解决方案

是否可以提供一个casdoor生产部署的docker-compose的参考文件

### 📝 补充信息

是否可以提供一个casdoor生产部署的docker-compose的参考文件

**Comment by arvinxx** [comment]
等 #3855

**Comment by zhangleijun111** [comment]
> 等 #3855

好的呀。那我问下casdoor支持生产环境的是吧

**Comment by SpeedupMaster** [comment]
docker-compose.yml
```
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lobe
      - POSTGRES_PASSWORD=b750e83ac80f7261513axxxxxxxxx
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./s3_data:/etc/minio/data
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=
      - MINIO_DOMAIN=
      - MINIO_API_CORS_ALLOW_ORIGIN=
    restart: always
    command: |
      server /etc/minio/data --address ":9000" --console-address ":9001"

  casdoor:
    image: casbin/casdoor:latest
    container_name: lobe-casdoor
    ports:
      - 8000:8000
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - RUNNING_IN_DOCKER=true
      - driverName=postgres
      - dataSourceName=postgres://postgres:b750e83ac80f7261513axxxxxxxxx@postgresql:5432/casdoor?sslmode=disable
    volumes:
      - ./files:/files
    entrypoint:
      - /bin/sh
      - -c
      - ./server --createDatabase=true
      
  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-database
    ports:
      - 3210:3210
    depends_on:
      - postgresql
      - minio
      - casdoor
    env_file:
      - .env
    restart: always
volumes:
  data:
    driver: local
  s3_data:
    driver: local
networks: {}
```
.env
```
# LobeChat 域名
APP_URL=

# Postgres 相关，也即 DB 必须的环境变量
# 用于加密敏感信息的密钥，可以使用 openssl rand -base64 32 生成
KEY_VAULTS_SECRET=
# Postgres 数据库连接字符串
DATABASE_URL=postgresql://postgres:b750e83ac80f7261513axxxxxxxxx@postgresql:5432/lobe

# NEXT_AUTH 相关
AUTH_URL=
NEXT_AUTH_SECRET=
NEXT_AUTH_SSO_PROVIDERS=casdoor
AUTH_CASDOOR_ID=
AUTH_CASDOOR_SECRET=
AUTH_CASDOOR_ISSUER=
CASDOOR_WEBHOOK_SECRET=

# MinIO S3 配置
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
S3_ENDPOINT=
S3_BUCKET=lobe 
S3_PUBLIC_DOMAIN=
S3_ENABLE_PATH_STYLE=1
```
