### ISSUE TITLE
[Bug] 无法上传文件

### ISSUE THREAD

**Issue by BiFangKNT** [lobehub/lobe-chat#4158]
### 📦 部署环境

Docker

### 📌 软件版本

lobehub/lobe-chat-database:1.19.34

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

不知道为什么突然无法上传文件了
![image](https://github.com/user-attachments/assets/4f568bdb-df69-4f9b-88fd-451fd9f77bb1)

五天前还是可以的
![image](https://github.com/user-attachments/assets/bd00d257-4060-40de-9bea-4535d5a49b82)

lobe和minio都没有报错

### 📷 复现步骤

数据库版，上传文件

### 🚦 期望结果

能够正常上传文件

### 📝 补充信息

并不是最新版本的问题，之前的v1.19.31也是不行。

**Comment by BiFangKNT** [comment]
并不是最新版本的问题，之前的v1.19.31也是不行。

**Comment by BiFangKNT** [comment]
报了CORS错误，但是我除了升级版本，没动过项目，五天前还是可以上传的啊
![image](https://github.com/user-attachments/assets/13b016ac-0e16-4154-9eb1-7f37ea5b3f84)
![image](https://github.com/user-attachments/assets/189c056b-6902-443e-8b97-ad08e0fd6666)

**Comment by BiFangKNT** [comment]
@dosu 已经做了`MINIO_API_CORS_ALLOW_ORIGIN`设置的：
```
  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - '19000:9000'
      - '19001:9001'
    volumes:
      - './s3_data:/data'
      - '/volume1/docker/lobechat/resolv.conf:/etc/resolv.conf:ro'
    environment:
      - 'MINIO_ROOT_USER=example'
      - 'MINIO_ROOT_PASSWORD=example'
      - 'MINIO_DOMAIN=minio.example.top'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=lobechat.example.top' # Your LobeChat's domain name.
    restart: always
    networks:
      - lobe
    command: >
      server /data --address ":9000" --console-address ":9001"
```

.env相关环境变量也一直都是配置了的：
```
# 必填，S3 的 Access Key ID，对于 MinIO 来说，直到在 MinIO UI 中手动创建之前都是无效的
S3_ACCESS_KEY_ID=example
# 必填，S3 的 Secret Access Key，对于 MinIO 来说，直到在 MinIO UI 中手动创建之前都是无效的
S3_SECRET_ACCESS_KEY=example
# 必填，S3 的 Endpoint，用于服务端/客户端连接到 S3 API
S3_ENDPOINT=https://minio.example.top
# 必填，S3 的 Bucket，直到在 MinIO UI 中手动创建之前都是无效的
S3_BUCKET=lobe
# 必填，S3 的 Public Domain，用于客户端通过公开连接访问非结构化数据
S3_PUBLIC_DOMAIN=https://minio.example.top
# 选填，S3 的 Enable Path Style
# 对于主流 S3 Cloud 服务商，一般填 0 即可；对于自部署的 MinIO，请填 1
# 请参考：https://lobehub.com/zh/docs/self-hosting/advanced/s3#s-3-enable-path-style
S3_ENABLE_PATH_STYLE=1
```
