### ISSUE TITLE
[Bug]  点击登录/注册 无法打开logto登录/注册页面

### ISSUE THREAD

**Issue by counghy** [lobehub/lobe-chat#4165]
### 📦 部署环境

Other

### 📌 软件版本

docker compse lobe-chat-database

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

使用 Docker Compose 部署 LobeChat 服务端数据库版本后，打开https://lobe.mydomain.com，点击登录/注册 无法打开logto登录/注册页面，过一会跳转到https://lobe.mydomain.com/api/auth/error?error=Configuration

浏览器请求：
![image](https://github.com/user-attachments/assets/dd9c3296-0b3c-4823-91be-fc5fb20f29d4)

docker 日志：
```
lobe_db           | [Database] Start to migration...
lobe_db           | ✅ database migration pass.
lobe_db           | -------------------------------------
lobe_db           |   ▲ Next.js 14.2.8
lobe_db           |   - Local:        http://localhost:3210
lobe_db           |   - Network:      http://0.0.0.0:3210
lobe_db           | 
lobe_db           |  ✓ Starting...
lobe_db           |  ✓ Ready in 92ms
lobe_db           | [auth][error] TypeError: fetch failed
lobe_db           |     at node:internal/deps/undici/undici:13178:13
lobe_db           |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lobe_db           |     at async ik (/app/.next/server/chunks/87862.js:368:44216)
lobe_db           |     at async iA (/app/.next/server/chunks/87862.js:368:46851)
lobe_db           |     at async iP (/app/.next/server/chunks/87862.js:368:49490)
lobe_db           |     at async i$ (/app/.next/server/chunks/87862.js:368:53705)
lobe_db           |     at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
lobe_db           |     at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
lobe_db           |     at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
lobe_db           |     at async doRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/server/base-server.js:1359:42)
lobe_db           | [NextAuth] Error: {
lobe_db           |   cause: 'Configuration',
lobe_db           |   message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
lobe_db           |   name: 'NextAuth Error'
lobe_db           | }
```

### 📷 复现步骤

docker-compose.yml
```
services:

  postgresql:
    image: postgres:16
    container_name: logto-postgres
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=logto'
      - 'POSTGRES_PASSWORD=logto'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  logto:
    image: svhd/logto:latest
    container_name: logto
    ports:
      - '127.0.0.1:3034:3034'
      - '127.0.0.1:3035:3035'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'PORT=3034'
      - 'ADMIN_PORT=3035'
      - 'TRUST_PROXY_HEADER=1'
      - 'DB_URL=postgresql://postgres:logto@postgresql:5432/logto'
      - 'ENDPOINT=https://lobe-auth-api.mydomain.com'
      - 'ADMIN_ENDPOINT=https://lobe-auth-ui.mydomain.com'
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']
    extra_hosts:
      - "lobe-auth-api.mydomain.com:172.17.0.1"
      - "lobe-auth-ui.mydomain.com:172.17.0.1"
```

```
services:

  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-db-postgres
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=lobe'
      - 'POSTGRES_PASSWORD=lobe'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe_db
    ports:
      - 127.0.0.1:3033:3210
    depends_on:
      postgresql:
        condition: service_healthy

    environment:
      - 'APP_URL=https://lobe.mydomain.com'
      - 'NEXT_AUTH_SSO_PROVIDERS=logto'
      - 'KEY_VAULTS_SECRET=NIdSgLKmeFhWmTuQKQYzn99oYk64aY0JTSssZuiWR8A=' #generate using `openssl rand -base64 32`
      - 'NEXT_AUTH_SECRET=+IHNVxT2qZpA8J+vnvuwA5Daqz4UFFJOahK6z/GsNIo=' #generate using `openssl rand -base64 32`
      - 'NEXTAUTH_URL=https://lobe.mydomain.com/api/auth'
      - 'AUTH_LOGTO_ISSUER=https://lobe-auth-api.mydomain.com/oidc' #Issuer endpoint
      - 'AUTH_LOGTO_ID=m7msb0eochw4c4qjox2w8' #App ID
      - 'AUTH_LOGTO_SECRET=cv91FK9kIvaPqf0X5pdVKVC3Uc9UqhZp' #App secrets
      - 'DATABASE_URL=postgresql://postgres:lobe@postgresql:5432/lobe'
      - 'POSTGRES_PASSWORD=lobe'
      - 'LOBE_DB_NAME=lobe'
      - 'S3_ENDPOINT=https://minio.mydomain.com'
      - 'S3_BUCKET=lobe'
      - 'S3_PUBLIC_DOMAIN=https://minio.mydomain.com'
      - 'S3_ACCESS_KEY_ID=xxxxx'
      - 'S3_SECRET_ACCESS_KEY=xxxxxx'
      - 'S3_ENABLE_PATH_STYLE=1'
      - 'OPENAI_API_KEY=sk-xxxxxx' #your OpenAI API Key
      - 'OPENAI_PROXY_URL=https://api.openai.com/v1'
      - 'OPENAI_MODEL_LIST=-all,+gpt-4o,+gpt-4o-mini,+claude-3-5-sonnet-20240620,+deepseek-chat,+o1-preview,+o1-mini' #change on your own needs, see https://lobehub.com/zh/docs/self-hosting/environment-variables/model-provider#openai-model-list
    restart: always
```

### 🚦 期望结果

正常打开logto登录/注册界面
