### ISSUE TITLE
[Bug] 使用PROXY_URL后DNS解析异常，导致生成的图片不显示

### ISSUE THREAD

**Issue by coulsontl** [lobehub/lobe-chat#4177]
### 📦 部署环境

Docker

### 📌 软件版本

lobehub/lobe-chat-database:latest

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

如图已经生成了图片链接，但是不展示
![image](https://github.com/user-attachments/assets/76fce6a0-d9cf-4245-a346-8b5ef34974df)

报错信息：
```
I: request to https://dalleprodsec.blob.core.windows.net/private/images/a9360a45-9ed7-4c8f-890b-deca69e17774/generated_00.png?se=2024-09-29T01%3A02%3A25Z&sig=XubsokFvLDAP9%2Bwc%2BhQ3ylWvSJkqyNAe%2FStmamtSiCo%3D&ske=2024-10-04T21%3A41%3A53Z&skoid=e52d5ed7-0657-4f62-bc12-7e5dbb260a96&sks=b&skt=2024-09-27T21%3A41%3A53Z&sktid=33e01921-4d64-4f8c-a055-5bdaffd5e33d&skv=2020-10-02&sp=r&spr=https&sr=b&sv=2020-10-02 failed, reason: DNS lookup 224.0.0.2(family:4, host:dalleprodsec.blob.core.windows.net) is not allowed. Because, It is private IP address.
    at ClientRequest.<anonymous> (/app/.next/server/app/webapi/proxy/route.js:1:17439)
    at ClientRequest.emit (node:events:519:28)
    at emitErrorEvent (node:_http_client:108:11)
    at TLSSocket.socketErrorListener (node:_http_client:511:5)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: undefined,
  code: undefined,
  erroredSysCall: undefined
}
```

进到容器内部nslookup
```
$ nslookup dalleprodsec.blob.core.windows.net
Server:     114.114.114.114
Address:    114.114.114.114:53

Non-authoritative answer:
dalleprodsec.blob.core.windows.net  canonical name = blob.gvx01prdstrz04a.store.core.windows.net
blob.gvx01prdstrz04a.store.core.windows.net canonical name = blob.gvx01prdstrz04a.trafficmanager.net

Non-authoritative answer:
dalleprodsec.blob.core.windows.net  canonical name = blob.gvx01prdstrz04a.store.core.windows.net
blob.gvx01prdstrz04a.store.core.windows.net canonical name = blob.gvx01prdstrz04a.trafficmanager.net
Name:   blob.gvx01prdstrz04a.trafficmanager.net
Address: 20.150.44.100
Name:   blob.gvx01prdstrz04a.trafficmanager.net
Address: 20.60.78.4
Name:   blob.gvx01prdstrz04a.trafficmanager.net
Address: 20.60.78.36
```

dns配置：
```
  lobe-chat:
    image: lobehub/lobe-chat-database:latest
    container_name: lobe-chat
    network_mode: bridge
    ports:
        - 3210:3210
    restart: always
    dns:
      - 114.114.114.114 # 114 DNS
      - 223.5.5.5 # Ali DNS
      - 119.29.29.29 # Tencent DNS
      - 8.8.8.8 # Google DNS
      - 1.1.1.1 #Cloudflare DNS
    environment:
    ……
```

### 📷 复现步骤

部署的是数据库版本，但是试过非数据库版本也不展示，docker的版本是最新的
