### ISSUE TITLE
lobechat不能切换头像

### ISSUE THREAD

**Issue by zeno980** [lobehub/lobe-chat#4700]
部署方案 casdoor
具体配置
docker-compose.yml
```
name: lobe-chat-database
services:
  network-service:
    image: alpine
    container_name: lobe-network
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}' # MinIO API
      - '9001:9001' # MinIO Console
      - '${CASDOOR_PORT}:8000' # Casdoor
      - '${LOBE_PORT}:3210' # LobeChat
    command: tail -f /dev/null
    networks:
      - lobe-network

  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - lobe-network

  minio:
    image: minio/minio
    container_name: lobe-minio
    network_mode: 'service:network-service'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ROOT_USER}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=https://lobe.example.cn'
    restart: always
    command: >
      server /etc/minio/data --address ":${MINIO_PORT}" --console-address ":9001"


  casdoor:
    image: casbin/casdoor
    container_name: lobe-casdoor
    entrypoint: /bin/sh -c './server --createDatabase=true'
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      RUNNING_IN_DOCKER: 'true'
      driverName: 'postgres'
      dataSourceName: 'user=postgres password=${POSTGRES_PASSWORD} host=postgresql port=5432 sslmode=disable dbname=casdoor'
      origin: 'https://lobe-auth-ui.example.cn'
      runmode: 'dev'
    volumes:
      - ./init_data.json:/init_data.json

  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-chat
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
      network-service:
        condition: service_started
      minio:
        condition: service_started
      casdoor:
        condition: service_started

    environment:
      - 'APP_URL=https://lobe.example.cn'
      - 'NEXT_AUTH_SSO_PROVIDERS=casdoor'
      - 'KEY_VAULTS_SECRET=***‘
      - 'NEXT_AUTH_SECRET=***'
      - 'AUTH_URL=https://lobe.example.cn/api/auth'
      - 'AUTH_CASDOOR_ID=${AUTH_CASDOOR_ID}'
      - 'AUTH_CASDOOR_SECRET=${AUTH_CASDOOR_SECRET}'
      - 'AUTH_CASDOOR_ISSUER=https://lobe-auth-ui.example.cn'
      - 'CASDOOR_WEBHOOK_SECRET=*'
      - 'NEXTAUTH_URL=https://lobe.example.cn/api/auth'
      - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/${LOBE_DB_NAME}'
      - 'S3_ENDPOINT=https://lobe-s3-api.example.cn'
      - 'S3_BUCKET=${MINIO_LOBE_BUCKET}'
      - 'S3_PUBLIC_DOMAIN=https://lobe-s3-api.example.cn'
      - 'S3_ENABLE_PATH_STYLE=1'
      - 'LLM_VISION_IMAGE_USE_BASE64=1'
    env_file:
      - .env
    restart: always

volumes:
  data:
    driver: local
  s3_data:
    driver: local

networks:
  lobe-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fc00:0:0:2::/64
          gateway: fc00:0:0:2::1
```

env文件
```
LOBE_PORT=3210
CASDOOR_PORT=8101
MINIO_PORT=9000

# Postgres related, which are the necessary environment variables for DB
LOBE_DB_NAME=lobechat
POSTGRES_PASSWORD=***

# Casdoor secret
AUTH_CASDOOR_ID=***
AUTH_CASDOOR_SECRET=***

# MinIO S3 configuration
MINIO_ROOT_USER=***
MINIO_ROOT_PASSWORD=***

# Configure the bucket information of MinIO
MINIO_LOBE_BUCKET=lobe
S3_ACCESS_KEY_ID=***
S3_SECRET_ACCESS_KEY=***
```
现象：部署后除了头像功能都正常，casdoor上传文件也正常，但我在casdoor配置中更改了用户头像，在lobe.example.cn中不会改动，还是初始的头像，经过casdoor api测试，casdoor可以正常返回用户的头像信息，但是在lobe.example.cn中的session接口中返回的image是不对的，返回了初始头像
