### ISSUE TITLE
[Bug] Docker Compose 部署 LobeChat 服务端，使用域名模式部署，为什么部署完成后访问 auth-ui 页面，一直被重定向对话

### ISSUE THREAD

**Issue by SarcomTDG** [lobehub/lobe-chat#4892]
### 📦 部署环境

Docker

### 📌 软件版本

last

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

Docker Compose 部署 LobeChat 服务端，使用域名模式部署，为什么部署完成后访问auth-ui页面，一直被重定向缺失对话
![image](https://github.com/user-attachments/assets/4481e971-5dbb-41fa-bcfc-1097804d9c5b)
![image](https://github.com/user-attachments/assets/92ae24ee-8abe-4c24-bf4d-5ea2d747bb18)

### 🚦 期望结果

登录LobeChat webui平台

**Comment by SarcomTDG** [comment]
登录鉴权使用默认  Logto ，通过ip＋端口访问也有相同问题

**Comment by SpeedupMaster** [comment]
域名是解析在Cloudflare上吗？

**Comment by SarcomTDG** [comment]
> 域名是解析在Cloudflare上吗？

不是，我是放到阿里云上面，域名指向服务器ip，通过nginx转发到内网里面另外一台服务器上，再通过这台服务器nginx转发到指定端口。

**Comment by SpeedupMaster** [comment]
> > 域名是解析在Cloudflare上吗？
> 
> 不是，我是放到阿里云上面，域名指向服务器ip，通过nginx转发到内网里面另外一台服务器上，再通过这台服务器nginx转发到指定端口。

不然试试casdoor吧，Logto部署好像一堆问题。

**Comment by SarcomTDG** [comment]
> > > 域名是解析在Cloudflare上吗？
> > 
> > 
> > 不是，我是放到阿里云上面，域名指向服务器ip，通过nginx转发到内网里面另外一台服务器上，再通过这台服务器nginx转发到指定端口。
> 
> 或者试试casdoor吧，Logto部署了很多问题。

通过域名发布 casdoor有相关参考文档和docker-compose.yml吗？

**Comment by SpeedupMaster** [comment]
> > > > 域名是解析在Cloudflare上吗？
> > > 
> > > 
> > > 不是，我是放到阿里云上面，域名指向服务器ip，通过nginx转发到内网里面另外一台服务器上，再通过这台服务器nginx转发到指定端口。
> > 
> > 
> > 或者试试casdoor吧，Logto部署了很多问题。
> 
> 通过域名发布 casdoor有相关参考文档和docker-compose.yml吗？

```
  casdoor:
    image: casbin/casdoor:latest
    container_name: lobe-casdoor
    ports:
      - 8000:8000
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - RUNNING_IN_DOCKER=true
      - driverName=postgres
      - dataSourceName=postgres://postgres:b750e83ac80f7261513axxxxxxxxx@postgresql:5432/casdoor?sslmode=disable
    volumes:
      - ./files:/files
    entrypoint:
      - /bin/sh
      - -c
      - ./server --createDatabase=true
```
环境变量
```
NEXT_AUTH_SSO_PROVIDERS=casdoor
AUTH_CASDOOR_ID=
AUTH_CASDOOR_SECRET=
AUTH_CASDOOR_ISSUER=
CASDOOR_WEBHOOK_SECRET=
```
记得要在casdoor里设置callback
`http://lobe.example.com/api/auth/callback/casdoor`
可以参考教程发布到IP那部分
