### ISSUE TITLE
[Bug] chat history has been lost when I go to another topic

### ISSUE THREAD

**Issue by konghui** [lobehub/lobe-chat#5065]
### 📦 Environment

Docker

### 📌 Version

1.36.32

### 💻 Operating System

Other Linux, Other

### 🌐 Browser

Edge

### 🐛 Bug Description

When I go to another topic and then click back. All the history messages have been lost. I can find all the history chat messages on PostgreSQL. 
I send some messages to the chatbot
![image](https://github.com/user-attachments/assets/084e1334-2037-419f-a7d9-a03a0e20eb34)
when I go to another topic and back. I can't find any history message.
![image](https://github.com/user-attachments/assets/fc201edd-5bab-4ef5-9cda-aed60a2e779f)
I can't find any error request on the HTTP request. But I can find an error on the console.
![image](https://github.com/user-attachments/assets/ad24e0e1-606b-487b-8f68-8f0cefc33f38)
I can find the history message on the PostgreSQL database;
![image](https://github.com/user-attachments/assets/e3ea00e4-10d8-4a6e-a6cd-9d8d323f3852)

### 📷 Recurrence Steps

1. Send a message to the chatbot.
2. Click another topic.
3. Back to the old one. You can't find any messages.

### 🚦 Expected Behavior

The history messages should be displayed.

### 📝 Additional Information

docker-file
```
  lobe-chat:
    image: lobehub/lobe-chat-database:v1.36.32
    container_name: lobe-chat
    environment:
      OPENROUTER_API_KEY: 'sk-or-xxx'
      OPENROUTER_MODEL_LIST: '-all,+openai/gpt-4o-2024-11-20,+openai/gpt-4o-2024-08-06,+openai/gpt-4o-mini-2024-07-18,+openai/gpt-4o,+openai/gpt-4-turbo,+anthropic/claude-3.5-haiku-20241022,+anthropic/claude-3.5-sonnet,+google/gemini-2.0-flash-exp:free,+meta-llama/llama-3.2-3b-instruct:free,+deepseek/deepseek-chat'
      APP_URL: 'https://xxx'
      KEY_VAULTS_SECRET: 'xxxxxx'
      DATABASE_URL: 'postgresql://lobechat:xxxx@postgres:5432/lobechat'
      NEXT_AUTH_SECRET: 'xxxx'
      NEXT_AUTH_SSO_PROVIDERS: 'logto'
      NEXTAUTH_URL: 'https://xxx/api/auth'
      AUTH_LOGTO_ID: 'xxxx'
      AUTH_LOGTO_SECRET: 'xxx
      AUTH_LOGTO_ISSUER: 'https://xxxx/oidc'
      S3_ENDPOINT: 'https://xxxx'
      S3_BUCKET: 'lobe-chat'
      S3_PUBLIC_DOMAIN: 'https://xxxx
      S3_ACCESS_KEY_ID: 'xxxxxx'
      S3_SECRET_ACCESS_KEY: 'xxxxx'
      S3_ENABLE_PATH_STYLE: '1'
      LLM_VISION_IMAGE_USE_BASE64: '1'
    ports: []
    restart: always
    depends_on:
      - postgres
      - logto
      - minio
```
