### ISSUE TITLE
[Bug] lobe-chat-db使用compose线上部署，logto启动后自动退出（其他服务正常）  #4009 

### ISSUE THREAD

**Issue by Silas-Xu** [lobehub/lobe-chat#5067]
### 📦 Environment

Docker

### 📌 Version

v1.36.33

### 💻 Operating System

Ubuntu

### 🌐 Browser

Edge

### 🐛 Bug Description

这个bug本来在 #4009 中解决，解决方案是指定Logto的版本为1.19.0，然而当我将`lobe-chat-db`更新到最新的`v1.36.33`后，即使采用指定版本的Logto，仍然无法正常启动Logto，异常信息与 #4009 相同。
是需要做一些额外的改动吗，如果改用casdoor的方案替换logto，能在部署文档中提供一下详细步骤吗？（部署文档中的域名模式只提供了Logto的配置方式，希望能增加casdoor的方式🙏）

**Comment by arvinxx** [comment]
大概率跟 LobeChat 没关系，建议检查下 logto 的配置

**Comment by SpeedupMaster** [comment]
先退回之前的版本，看下能不能正常启动，然后进入logto容器手动更新数据库。

**Comment by Silas-Xu** [comment]
logto版本用1.19.0和latest都没成功。
更新前：logto==1.19.0, lobe==1.36.22 可以启动成功
更新后：logto==1.19.0, lobe==1.36.33 无法启动成功
更新时没有对配置做任何更改。
（已暂时回退到更新前的版本了）

**Comment by SpeedupMaster** [comment]
casdoor可以参考这个
```
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lobe
      - POSTGRES_PASSWORD=b750e83ac80f7261513axxxxxxxxx
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./s3_data:/etc/minio/data
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=
      - MINIO_DOMAIN=
      - MINIO_API_CORS_ALLOW_ORIGIN=
    restart: always
    command: |
      server /etc/minio/data --address ":9000" --console-address ":9001"

  casdoor:
    image: casbin/casdoor:latest
    container_name: lobe-casdoor
    ports:
      - 8000:8000
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - RUNNING_IN_DOCKER=true
      - driverName=postgres
      - dataSourceName=postgres://postgres:b750e83ac80f7261513axxxxxxxxx@postgresql:5432/casdoor?sslmode=disable
    volumes:
      - ./files:/files
    entrypoint:
      - /bin/sh
      - -c
      - ./server --createDatabase=true
      
  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-database
    ports:
      - 3210:3210
    depends_on:
      - postgresql
      - minio
      - casdoor
    env_file:
      - .env
    restart: always
volumes:
  data:
    driver: local
  s3_data:
    driver: local
networks: {}
```
