### ISSUE TITLE
[Bug] 数据库模式只有上传图片有问题。

### ISSUE THREAD

**Issue by CoREse** [lobehub/lobe-chat#5252]
### 📦 部署环境

Docker

### 📌 软件版本

1.42.1

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

我的网络也无法开启443端口，所以按照 #4745 里的方法成功地用其它端口搭建起来了。注册登录，发消息，上传除图片之外的文件都使用正常，但唯独上传图片，会显示“文件上传失败”，并且上传失败，无论是粘贴图片，还是使用“上传图片”或是“上传文件“，只要是图片文件就不行。我看了一下调试模式的网络，它会显示`PUT https://[mydomain:myport]/lobe/files/482143/11af242f-ad3f-40a1-b81d-e52d284d7483.JPG?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=qsFyo24b1yEvkHoGVA4t%2F20250101%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250101T064918Z&X-Amz-Expires=3600&X-Amz-Signature=9fe6cd4f2425fb5c07af96d0bbebf264fdf90aa332407487730a1418f76f0cfa&X-Amz-SignedHeaders=host&x-amz-acl=public-read&x-id=PutObject 403 (Forbidden)`。不知道是什么原因，请教一下诸位大佬。感谢！

### 📷 复现步骤

上传图片

### 🚦 期望结果

成功上传

### 📝 补充信息

这里附上我的docker-compose和.env

docker-compose.yml:
```
services:
  network-service:
    image: alpine
    container_name: lobe-network
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}' # MinIO API
      - '9001:9001' # MinIO Console
      - '${CASDOOR_PORT}:${CASDOOR_PORT}' # Casdoor
      - '${LOBE_PORT}:3210' # LobeChat
    command: tail -f /dev/null
    networks:
      - lobe-network

  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - lobe-network

  minio:
    image: minio/minio
    container_name: lobe-minio
    network_mode: 'service:network-service'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ROOT_USER}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=https://lobe.[mydomain:myport]'
    restart: always
    command: >
      server /etc/minio/data --address ":${MINIO_PORT}" --console-address ":9001"


  casdoor:
    image: casbin/casdoor
    container_name: lobe-casdoor
    entrypoint: /bin/sh -c './server --createDatabase=true'
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      RUNNING_IN_DOCKER: 'true'
      driverName: 'postgres'
      dataSourceName: 'user=postgres password=${POSTGRES_PASSWORD} host=postgresql port=5432 sslmode=disable dbname=casdoor'
      origin: 'https://lobe-auth-api.[mydomain:myport]'
      runmode: 'dev'
        #volumes:
        #- ./init_data.json:/init_data.json

  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-chat
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
      network-service:
        condition: service_started
      minio:
        condition: service_started
      casdoor:
        condition: service_started

    environment:
      - 'APP_URL=https://lobe.[mydomain:myport]'
      - 'NEXT_AUTH_SSO_PROVIDERS=casdoor'
      - 'KEY_VAULTS_SECRET=[MYSECRET]'
      - 'NEXT_AUTH_SECRET=[MYSECRET]'
      - 'AUTH_URL=https://lobe.[mydomain:myport]/api/auth'
      - 'AUTH_CASDOOR_ISSUER=https://lobe-auth-api.[mydomain:myport]'
      - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/${LOBE_DB_NAME}'
      - 'S3_ENDPOINT=https://lobe-s3-api.[mydomain:myport]'
      - 'S3_BUCKET=${MINIO_LOBE_BUCKET}'
      - 'S3_PUBLIC_DOMAIN=http://lobe-s3-api.[mydomain:myport]'
      - 'S3_ENABLE_PATH_STYLE=1'
      - 'LLM_VISION_IMAGE_USE_BASE64=1'
    env_file:
      - .env
    restart: always

volumes:
  data:
    driver: local
  s3_data:
    driver: local

networks:
  lobe-network:
    driver: bridge
```

.env:
```
COMPOSE_PROJECT_NAME=lobe-chat-database
# Proxy, if you need it
# HTTP_PROXY=http://localhost:7890
# HTTPS_PROXY=http://localhost:7890


# Other environment variables, as needed. You can refer to the environment variables configuration for the client version, making sure not to have ACCESS_CODE.
# OPENAI_API_KEY=sk-xxxx
# OPENAI_PROXY_URL=https://api.openai.com/v1
# OPENAI_MODEL_LIST=...


# ===========================
# ====== Preset config ======
# ===========================
# if no special requirements, no need to change
LOBE_PORT=3210
CASDOOR_PORT=8000
MINIO_PORT=9000

# Postgres related, which are the necessary environment variables for DB
LOBE_DB_NAME=lobechat
POSTGRES_PASSWORD=[MYSECRET]

# Casdoor secret
AUTH_CASDOOR_ID=[MYSECRET]
AUTH_CASDOOR_SECRET=[MYSECRET]

# MinIO S3 configuration
MINIO_ROOT_USER=[MYSECRET]
MINIO_ROOT_PASSWORD=[MYSECRET]

# Configure the bucket information of MinIO
MINIO_LOBE_BUCKET=lobe
#S3_ACCESS_KEY_ID=soaucnP8Bip0TDdUjxng
#S3_SECRET_ACCESS_KEY=ZPUzvY34umfcfxvWKSv0P00vczVMB6YmgJS5J9eO
S3_ACCESS_KEY_ID=[MYSECRET]
S3_SECRET_ACCESS_KEY=[MYSECRET]

OPENAI_API_KEY=[MYSECRET]
OPENAI_PROXY_URL=https://aihubmix.com/v1 
```
