### ISSUE TITLE
[Bug] 502BadGateway求助，数据库版本，升级到最新版本后无法正常访问，容器反复重启

### ISSUE THREAD

**Issue by jorben** [lobehub/lobe-chat#5262]
### 📦 部署环境

Docker

### 📌 软件版本

v1.42.3

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

错误日志：
```
lobe_postgres  | 
lobe_postgres  | PostgreSQL Database directory appears to contain a database; Skipping initialization
lobe_postgres  | 
lobe_postgres  | 2025-01-02 08:00:47.733 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
lobe_postgres  | 2025-01-02 08:00:47.733 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
lobe_postgres  | 2025-01-02 08:00:47.733 UTC [1] LOG:  listening on IPv6 address "::", port 5432
lobe_postgres  | 2025-01-02 08:00:47.738 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
lobe_postgres  | 2025-01-02 08:00:47.746 UTC [28] LOG:  database system was shut down at 2025-01-02 07:54:47 UTC
lobe_postgres  | 2025-01-02 08:00:47.764 UTC [1] LOG:  database system is ready to accept connections
lobe_server    | 🌐 DNS Server: [ '127.0.0.11' ]
lobe_server    | -------------------------------------
lobe_server    | [Database] Start to migration...
lobe_server    | ✅ database migration pass.
lobe_server    | -------------------------------------
lobe_server    |    ▲ Next.js 15.1.3
lobe_server    |    - Local:        http://localhost:3210
lobe_server    |    - Network:      http://0.0.0.0:3210
lobe_server    | 
lobe_server    |  ✓ Starting...
lobe_server    |  ✓ Ready in 178ms
lobe_server    | {
lobe_server    |   allowDangerousEmailAccountLinking: true,
lobe_server    |   clientId: undefined,
lobe_server    |   clientSecret: undefined,
lobe_server    |   platformType: 'WebsiteApp',
lobe_server    |   profile: [Function: profile]
lobe_server    | }
lobe_server    | (node:28) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
lobe_server    | (Use `node --trace-deprecation ...` to show where the warning was created)
lobe_server    | {
lobe_server    |   allowDangerousEmailAccountLinking: true,
lobe_server    |   clientId: undefined,
lobe_server    |   clientSecret: undefined,
lobe_server    |   platformType: 'WebsiteApp',
lobe_server    |   profile: [Function: profile]
lobe_server    | }
lobe_server    | /app/startServer.js:88
lobe_server    |     process.on('close', (code) => (code === 0 ? resolve() : reject(new Error(`🔴 Process exited with code ${code}`))));
lobe_server    |                                                                    ^
lobe_server    | 
lobe_server    | Error: 🔴 Process exited with code null
lobe_server    |     at ChildProcess.<anonymous> (/app/startServer.js:88:68)
lobe_server    |     at ChildProcess.emit (node:events:524:28)
lobe_server    |     at maybeClose (node:internal/child_process:1101:16)
lobe_server    |     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
lobe_server    | 
lobe_server    | Node.js v22.12.0
lobe_server exited with code 1
```
docker-compose.yml
```
name: lobe

services:

  server:
    image: lobehub/lobe-chat-database
    container_name: lobe_server
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      inner-net:
        priority: 10
      my-net:
        priority: 20
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    container_name: lobe_postgres
    volumes:
      - '/data/volumes/lobe/db:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=lobe'
      - 'POSTGRES_PASSWORD=**********'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - inner-net
    restart: always
```
.env
```
# 必填，LobeChat 域名，用于 tRPC 调用
# 请保证此域名在你的 NextAuth 鉴权服务提供商、S3 服务商的 CORS 白名单中
APP_URL=https://ai.testtest.com/

# Postgres 相关，也即 DB 必需的环境变量
# 必填，用于加密敏感信息的密钥，可以使用 openssl rand -base64 32 生成
KEY_VAULTS_SECRET=*******/**********=
# 必填，Postgres 数据库连接字符串，用于连接到数据库
# 格式：postgresql://username:password@host:port/dbname，如果你的 pg 实例为 Docker 容器且位于同一 docker-compose 文件中，亦可使用容器名作为 host
DATABASE_URL=postgresql://postgres:*******@lobe_postgres:5432/lobe

# NEXT_AUTH 相关，也即鉴权服务必需的环境变量
# 可以使用 auth0、Azure AD、GitHub、Authentik、Zitadel、Logto 等，如有其他接入诉求欢迎提 PR
# 目前支持的鉴权服务提供商请参考：https://lobehub.com/zh/docs/self-hosting/advanced/auth#next-auth
# 如果你有 ACCESS_CODE，请务必清空，我们以 NEXT_AUTH 作为唯一鉴权来源
# 必填，用于 NextAuth 的密钥，可以使用 openssl rand -base64 32 生成
NEXT_AUTH_SECRET=******/*******=
# 必填，指定鉴权服务提供商，这里以 Logto 为例
NEXT_AUTH_SSO_PROVIDERS=logto
# 必填，NextAuth 的 URL，用于 NextAuth 的回调
NEXTAUTH_URL=https://ai.testtest.com/api/auth

# NextAuth 鉴权服务提供商部分，以 Logto 为例
# 其他鉴权服务提供商所需的环境变量，请参考：https://lobehub.com/zh/docs/self-hosting/environment-variables/auth
AUTH_LOGTO_ID=***********
AUTH_LOGTO_SECRET=********
AUTH_LOGTO_ISSUER=https://auth.testtest.com/oidc
LOGTO_WEBHOOK_SIGNING_KEY=************

# S3 相关，也即非结构化数据（文件、图片等）存储必需的环境变量
# 这里以 MinIO 为例
# 必填，S3 的 Access Key ID，对于 MinIO 来说，直到在 MinIO UI 中手动创建之前都是无效的
S3_ACCESS_KEY_ID=**********
# 必填，S3 的 Secret Access Key，对于 MinIO 来说，直到在 MinIO UI 中手动创建之前都是无效的
S3_SECRET_ACCESS_KEY=********
# 必填，S3 的 Endpoint，用于服务端/客户端连接到 S3 API
S3_ENDPOINT=https://cos.ap-guangzhou.myqcloud.com
# 必填，S3 的 Bucket，直到在 MinIO UI 中手动创建之前都是无效的
S3_BUCKET=public-******
# 必填，S3 的 Public Domain，用于客户端通过公开连接访问非结构化数据
# S3_PUBLIC_DOMAIN=https://s3-123.****.com
S3_PUBLIC_DOMAIN=https://public-******.cos.ap-guangzhou.myqcloud.com
# 选填，S3 的 Enable Path Style
# 对于主流 S3 Cloud 服务商，一般填 0 即可；对于自部署的 MinIO，请填 1
# 请参考：https://lobehub.com/zh/docs/self-hosting/advanced/s3#s-3-enable-path-style
S3_ENABLE_PATH_STYLE=0
```

### 🚦 期望结果

正常访问
