### ISSUE TITLE
[Bug] 启动多个next-server服务进程，占用内存

### ISSUE THREAD

**Issue by mt-altman** [lobehub/lobe-chat#5363]
### 📦 部署环境

Docker

### 📌 软件版本

lobehub / lobe-chat-database

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

<img width="990" alt="image" src="https://github.com/user-attachments/assets/1ea7ad0f-1c70-49a6-8781-d5eae68ef9f4" />
会启动多个next-server服务进程，占用内存挺大的

### 📷 复现步骤

- docker启动后能复现

### 📝 补充信息

docker-compose.yml
```
version: '3.8'
services:
  lobe-chat:
    image: lobehub/lobe-chat-database
    restart: always
    environment:
      ACCESS_CODE: *****32a
      APP_URL: https://xxx.com
      AUTH_AUTH0_ID: ******2U
      AUTH_AUTH0_SECRET: *****k
      AUTH_AUTH0_ISSUER: https://***.auth0.com
      TZ: Asia/Shanghai
      DATABASE_DRIVER: node
      DATABASE_URL: postgresql://*****/lobe_chat?sslmode=require
      KEY_VAULTS_SECRET: ****k=
      NEXT_AUTH_SECRET: ***cb
      NEXT_AUTH_SSO_PROVIDERS: auth0
      NEXTAUTH_URL: https://***.com/api/auth
      OPENAI_API_KEY: ****9b
      OPENAI_MODEL_LIST: -all,+claude-3-opus-20240229,+claude-3-sonnet-20240229,+claude-3-5-sonnet-20240620,+claude-3-5-sonnet-20241022,+claude-3-haiku-20240307,+gpt-4o,+gpt-4o-mini,+gpt-4-turbo,gemini-1.5-pro-latest,gemini-exp-1206,gemini-2.0-flash-thinking-exp,gemini-2.0-flash-exp,deepseek-chat,+FLUX-pro,jimeng-2.1
      OPENAI_PROXY_URL: https://*****.com/v1
      S3_ACCESS_KEY_ID: ****3
      S3_BUCKET: lobechat
      S3_ENDPOINT: https://****.com
      S3_PUBLIC_DOMAIN: https://*****.com
      S3_SECRET_ACCESS_KEY: *****2
    ports:
      - 3210:3210
```
_No response_
