### ISSUE TITLE
[Bug] 数据库版本无法认证，跳转 `api/auth/error `

### ISSUE THREAD

**Issue by JoeChen2me** [lobehub/lobe-chat#5437]
### 📦 Environment

Docker

### 📌 Version

v1.45.8

### 💻 Operating System

Ubuntu

### 🌐 Browser

Edge

### 🐛 Bug Description

使用域名方式部署运行 数据库版本时，经过以下尝试，使用
1. casdoor
2. logto
3. github
以上三种方式都会出现错误，点击登录/注册时，直接跳转到`https://lobe.Mydomain.com/api/auth/error` 
![image](https://github.com/user-attachments/assets/adad5e0c-871a-45e5-be4e-36a2b50a8b45)
在配置过程中，均遵循官方教程文档进行配置  [教程文档](https://lobehub.com/zh/docs/self-hosting/advanced/auth/next-auth/)。下图以casdoor的配置为例子：
![image](https://github.com/user-attachments/assets/1b237145-d524-40c2-bd2a-4341ef19655f)
![image](https://github.com/user-attachments/assets/a57d6db0-3bf3-423d-868e-27fb4df66b72)
![image](https://github.com/user-attachments/assets/0f8e577e-c0d8-4de2-bf25-943d7432d4d8)
均已按照教程进行了配置。
但这三种方式都会出现上述登录/注册失败的情况。
Nginx的 反代已经设置完毕，认证端和S3端和主页面都可以进行通过域名访问
详细的配置文件在下方放出。
请问这是什么原因呢？
- `.env`文件
```yaml
CASDOOR_PORT=8000
# 必填，LobeChat 域名，用于 tRPC 调用
# 请保证此域名在你的 NextAuth 鉴权服务提供商、S3 服务商的 CORS 白名单中
APP_URL=https://lobe.mydomain.com/

# Postgres 相关，也即 DB 必需的环境变量
# 必填，用于加密敏感信息的密钥，可以使用 openssl rand -base64 32 生成
KEY_VAULTS_SECRET=Kix2wcUONd4CX51E/ZPAd36BqM4wzJgKjPtz2sGztqQ=
# 必填，Postgres 数据库连接字符串，用于连接到数据库
# 格式：postgresql://username:password@host:port/dbname，如果你的 pg 实例为 Docker 容器且位于同一 docker-compose 文件中，亦可使用容器名作为 host
DATABASE_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/lobe

# NEXT_AUTH 相关，也即鉴权服务必需的环境变量
# 可以使用 auth0、Azure AD、GitHub、Authentik、Zitadel、Logto 等，如有其他接入诉求欢迎提 PR
# 目前支持的鉴权服务提供商请参考：https://lobehub.com/zh/docs/self-hosting/advanced/auth#next-auth
# 如果你有 ACCESS_CODE，请务必清空，我们以 NEXT_AUTH 作为唯一鉴权来源
# 必填，用于 NextAuth 的密钥，可以使用 openssl rand -base64 32 生成
# NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg
# # 必填，指定鉴权服务提供商，这里以 Logto 为例
# # NEXT_AUTH_SSO_PROVIDERS=logto # 不使用logto 
# NEXT_AUTH_SSO_PROVIDERS=github
# # 必填，NextAuth 的 URL，用于 NextAuth 的回调
# NEXTAUTH_URL=https://lobe.mydomain.com/api/auth

# # NextAuth 鉴权服务提供商部分，以 Logto 为例
# # 其他鉴权服务提供商所需的环境变量，请参考：https://lobehub.com/zh/docs/self-hosting/environment-variables/auth
# # 注释下面三行以取消Logto鉴权
# # AUTH_LOGTO_ID=f6ef6cyuyf9pfv44
# # AUTH_LOGTO_SECRET=bYBTljG8SinvOWqlPC
# # AUTH_LOGTO_ISSUER=https://lobe-auth-api.mydomain.com/oidc

# AUTH_GITHUB_ID = modified
# AUTH_GITHUB_SECRET = modified

# 代理相关，如果你需要的话（比如你使用 GitHub 作为鉴权服务提供商）
# HTTP_PROXY=http://localhost:7890
# HTTPS_PROXY=http://localhost:7890


# casdoor config
NEXT_AUTH_SECRET = NX2kaPE923dt6BL2U8e9oSre5RfoT7hg
NEXT_AUTH_SSO_PROVIDERS = casdoor
AUTH_CASDOOR_ID = cb5673418e9cbbc3ef90
AUTH_CASDOOR_SECRET = 06d6a0d11a5175501b300eb3f49691a8a163075b
AUTH_CASDOOR_ISSUER = https://lobe-casdoor.mydomain.com/
NEXTAUTH_URL = https://lobe.mydomain.com/api/auth


# S3 相关，也即非结构化数据（文件、图片等）存储必需的环境变量
# 这里以 MinIO 为例
# 必填，S3 的 Access Key ID，对于 MinIO 来说，直到在 MinIO UI 中手动创建之前都是无效的
S3_ACCESS_KEY_ID=gcuKWmkHFFeYnWVvnxgU
# 必填，S3 的 Secret Access Key，对于 MinIO 来说，直到在 MinIO UI 中手动创建之前都是无效的
S3_SECRET_ACCESS_KEY=7TMA2T9dvV8aIi9UEr8n7pGTluZEPDvUy5HG17t7
# 必填，S3 的 Endpoint，用于服务端/客户端连接到 S3 API
S3_ENDPOINT=https://lobe-s3-api.mydomain.com
# 必填，S3 的 Bucket，直到在 MinIO UI 中手动创建之前都是无效的
S3_BUCKET=lobe
# 必填，S3 的 Public Domain，用于客户端通过公开连接访问非结构化数据
S3_PUBLIC_DOMAIN=https://lobe-s3-api.mydomain.com
# 选填，S3 的 Enable Path Style
# 对于主流 S3 Cloud 服务商，一般填 0 即可；对于自部署的 MinIO，请填 1
# 请参考：https://lobehub.com/zh/docs/self-hosting/advanced/s3#s-3-enable-path-style
S3_ENABLE_PATH_STYLE=1


# casdoor config



# 其他基础环境变量，视需求而定。注意不要有 ACCESS_CODE
# 请参考：https://lobehub.com/zh/docs/self-hosting/environment-variables/basic
# 请注意，对于服务端版本，其 API 必须支持嵌入（即 OpenAI text-embedding-3-small）模型，否则无法对上传文件进行处理，但你无需在 OPENAI_MODEL_LIST 中指定此模型
# OPENAI_API_KEY=sk-xxxx
# OPENAI_PROXY_URL=https://api.openai.com/v1
# OPENAI_MODEL_LIST=...

# SET ollama
ENABLED_OLLAMA = 0

# set openai 
ENABLED_OPENAI = 0
OPENAI_MODEL_LIST=-all,+gpt-4o-mini


# set google proxy
ENABLED_GOOGLE = 1
GOOGLE_PROXY_URL = https://api-proxy.me/gemini


# set Deepseek
ENABLED_DEEPSEEK = 1

# set groq
ENABLED_GROQ = 1
GROQ_PROXY_URL =https://api-proxy.me/groq
```
- `.docker compose .yml`文件
```yaml
name: lobe-chat-database
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=lobe'
      - 'POSTGRES_PASSWORD=uWNZugjBqixf8dxC'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=JoeChen'
      - 'MINIO_ROOT_PASSWORD=Crj1570768'
      - 'MINIO_DOMAIN=lobe-s3-api.mydomain.com'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=https://lobe.mydomain.com' # Your LobeChat's domain name.
    restart: always
    command: >
      server /etc/minio/data --address ":9000" --console-address ":9001"

  casdoor:
    image: casbin/casdoor
    container_name: lobe-casdoor
    entrypoint: /bin/sh -c './server --createDatabase=true'
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - '8000:8000'
    environment:
      RUNNING_IN_DOCKER: 'true'
      driverName: 'postgres'
      dataSourceName: 'user=postgres password=uWNZugjBqixf8dxC host=postgresql port=5432 sslmode=disable dbname=casdoor'
      # origin: 'http://localhost:${CASDOOR_PORT}'
      origin: 'https://lobe-casdoor.mydomain.com'
      runmode: 'dev'
    volumes:
      - ./init_data.json:/init_data.json

  # logto:
  #   image: svhd/logto
  #   container_name: lobe-logto
  #   ports:
  #     - '3001:3001'
  #     - '3002:3002'
  #   depends_on:
  #     postgresql:
  #       condition: service_healthy
  #   environment:
  #     - 'TRUST_PROXY_HEADER=1'
  #     - 'DB_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/logto'
  #     - 'ENDPOINT=https://lobe-auth-api.mydomain.com'
  #     - 'ADMIN_ENDPOINT=https://lobe-auth-ui.mydomain.com'
  #   entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']

  lobe:
    image: lobehub/lobe-chat-database:latest
    container_name: lobe-chat
    ports:
      - '3210:3210'
    depends_on:
      # - postgresql
      # - minio
      # # - logto
      postgresql:
        condition: service_healthy
      minio:
        condition: service_started
      casdoor:
        condition: service_started
    env_file:
      - .env
    restart: always

volumes:
  data:
    driver: local
  s3_data:
    driver: local

```

### 📷 Recurrence Steps

配置Next-AUTH的相关环境变量
进入页面，点击 `登录/注册`
会跳转到 `/api/auth/error`
以上情况对三种验证服务均有效
1. casdoor
2. logto
3. github

### 🚦 Expected Behavior

点击`登录/注册`，会跳转到对应的认证接口
