### ISSUE TITLE
[Bug] 智谱Embedding模型 提示向量化失败

### ISSUE THREAD

**Issue by bunwen** [lobehub/lobe-chat#5452]
### 📦 部署环境

Docker

### 📌 软件版本

1.46.1

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome, Safari

### 🐛 问题描述

在对文件进行向量化时，智谱的API反馈为令牌已过期或不正确
<img width="848" alt="image" src="https://github.com/user-attachments/assets/db5412d5-11c2-481a-9be7-baffec47b44d" />
但是与此同时 Chat功能正常
<img width="1645" alt="image" src="https://github.com/user-attachments/assets/9ee22d66-8b1b-414f-8f9a-fd9f8802dfa7" />

### 📷 复现步骤

在完成.env环境变量的编辑后尝试进行文件向量化
环境变量： 
ZHIPU_API_KEY='xxxxxxxxxxx'
DEFAULT_FILES_CONFIG='embedding_model=zhipu/embedding-3'

### 🚦 期望结果

正常使用文件向量化

### 📝 补充信息

无

**Comment by arvinxx** [comment]
@cookieY 帮忙看看？

**Comment by cookieY** [comment]
> @cookieY 帮忙看看？

我看一下

**Comment by cookieY** [comment]
#5454

**Comment by bunwen** [comment]
版本1.46.7 问题依然存在

**Comment by cookieY** [comment]
我这测试没什么问题，需要给一下lobe-chat的运行日志信息

**Comment by bunwen** [comment]
> 我这测试没什么问题，需要给一下lobe-chat的运行日志信息
`    at W (/app/.next/server/edge-chunks/708.js:1:120802)
    at /app/.next/server/edge-chunks/708.js:1:123546
    at /app/.next/server/edge-chunks/708.js:1:130156
    at e.with (/app/.next/server/edge-chunks/708.js:1:10881)
    at e.with (/app/.next/server/edge-chunks/708.js:1:11949)
    at e.startActiveSpan (/app/.next/server/edge-chunks/708.js:1:14065)
    at e.startActiveSpan (/app/.next/server/edge-chunks/708.js:1:14363)
    at /app/.next/server/edge-chunks/708.js:1:129678 {
  
}
[AgentIndexFetchError] failed to fetch agent index, error detail:
Error: fetch failed
    at context.fetch (/app/node_modules/.pnpm/next@15.1.4_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-dom@19._7kkqdni7o67xieskmplqyk7xbe/node_modules/next/dist/server/web/sandbox/context.js:303:38)
    at /app/.next/server/edge-chunks/708.js:1:115781
    at W (/app/.next/server/edge-chunks/708.js:1:120802)
    at /app/.next/server/edge-chunks/708.js:1:123546
    at /app/.next/server/edge-chunks/708.js:1:130156
    at e.with (/app/.next/server/edge-chunks/708.js:1:10881)
    at e.with (/app/.next/server/edge-chunks/708.js:1:11949)
    at e.startActiveSpan (/app/.next/server/edge-chunks/708.js:1:14065)
    at e.startActiveSpan (/app/.next/server/edge-chunks/708.js:1:14363)
    at /app/.next/server/edge-chunks/708.js:1:129678 {
  
}
Error getting changelog lists: TypeError: fetch failed
    at async m.getChangelogIndex (.next/server/app/@modal/(.)changelog/modal/page.js:74:15454)
    at async m.getLatestChangelogId (.next/server/app/@modal/(.)changelog/modal/page.js:74:15313)
    at async g (.next/server/app/(main)/chat/(workspace)/page.js:1208:16171) {
  [cause]: [Error [ConnectTimeoutError]: Connect Timeout Error (attempted addresses: 185.199.109.133:443, 185.199.108.133:443, 185.199.111.133:443, timeout: 10000ms)] {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
embeddingChunks error n {
  name: 'TaskTimeout',
  body: { detail: 'embedding task is timeout, please try again' }
}
(node:27) Warning: Label '任务[1]: embeddings' already exists for console.time()
embeddingChunks error {
  message: '{"endpoint":"https://open.bigmodel.cn/api/paas/v4","error":{"status":401,"headers":{"connection":"keep-alive","content-length":"73","content-type":"application/json","date":"Fri, 17 Jan 2025 07:22:36 GMT","set-cookie":"acw_tc=784e2c9c17370985562708140e0fab1615967feabc127ef10c69590693c5d3;path=/;HttpOnly;Max-Age=1800","strict-transport-security":"max-age=31536000; includeSubDomains","vary":"Origin, Access-Control-Request-Method, Access-Control-Request-Headers","x-log-id":"202501171522361a10f4c5414b4819"},"error":{"code":"401","message":"令牌已过期或验证不正确！"},"code":"401"},"errorType":"InvalidProviderAPIKey","provider":"zhipu"}',
  name: 'EmbeddingError'
}
(node:27) Warning: Label '任务[1]: embeddings' already exists for console.time()
embeddingChunks error {
  message: '{"endpoint":"https://open.bigmodel.cn/api/paas/v4","error":{"status":401,"headers":{"connection":"keep-alive","content-length":"73","content-type":"application/json","date":"Fri, 17 Jan 2025 07:23:16 GMT","set-cookie":"acw_tc=ac11000117370985961602928e00761fce1bf2957710a2e1c9d385fa863222;path=/;HttpOnly;Max-Age=1800","strict-transport-security":"max-age=31536000; includeSubDomains","vary":"Origin, Access-Control-Request-Method, Access-Control-Request-Headers","x-log-id":"202501171523162d0096dca9794211"},"error":{"code":"401","message":"令牌已过期或验证不正确！"},"code":"401"},"errorType":"InvalidProviderAPIKey","provider":"zhipu"}',
  name: 'EmbeddingError'
}
(node:27) Warning: Label '任务[1]: embeddings' already exists for console.time()
embeddingChunks error {
  message: '{"endpoint":"https://open.bigmodel.cn/api/paas/v4","error":{"status":401,"headers":{"connection":"keep-alive","content-length":"73","content-type":"application/json","date":"Fri, 17 Jan 2025 07:23:41 GMT","set-cookie":"acw_tc=784e2ca617370986213095808e0e9990f055fecbd39a6f6346c686efe670b2;path=/;HttpOnly;Max-Age=1800","strict-transport-security":"max-age=31536000; includeSubDomains","vary":"Origin, Access-Control-Request-Method, Access-Control-Request-Headers","x-log-id":"2025011715234136ba247207d14c73"},"error":{"code":"401","message":"令牌已过期或验证不正确！"},"code":"401"},"errorType":"InvalidProviderAPIKey","provider":"zhipu"}',
  name: 'EmbeddingError'
}
(node:27) Warning: Label '任务[1]: embeddings' already exists for console.time()
embeddingChunks error {
  message: '{"endpoint":"https://open.bigmodel.cn/api/paas/v4","error":{"status":401,"headers":{"connection":"keep-alive","content-length":"73","content-type":"application/json","date":"Fri, 17 Jan 2025 07:24:33 GMT","set-cookie":"acw_tc=784e2c9717370986735078881e5fd77d1065fcaed6cb5a4e913c720af85294;path=/;HttpOnly;Max-Age=1800","strict-transport-security":"max-age=31536000; includeSubDomains","vary":"Origin, Access-Control-Request-Method, Access-Control-Request-Headers","x-log-id":"2025011715243343340c8f74bf4162"},"error":{"code":"401","message":"令牌已过期或验证不正确！"},"code":"401"},"errorType":"InvalidProviderAPIKey","provider":"zhipu"}',
  name: 'EmbeddingError'
}
(node:27) Warning: Label '任务[1]: embeddings' already exists for console.time()
embeddingChunks error {
  message: '{"endpoint":"https://open.bigmodel.cn/api/paas/v4","error":{"status":401,"headers":{"connection":"keep-alive","content-length":"73","content-type":"application/json","date":"Fri, 17 Jan 2025 07:24:37 GMT","set-cookie":"acw_tc=784e2c9717370986773341251e5fd7e62845eb3f31ba6846adcd4af156339a;path=/;HttpOnly;Max-Age=1800","strict-transport-security":"max-age=31536000; includeSubDomains","vary":"Origin, Access-Control-Request-Method, Access-Control-Request-Headers","x-log-id":"202501171524372d71272f27dc4c41"},"error":{"code":"401","message":"令牌已过期或验证不正确！"},"code":"401"},"errorType":"InvalidProviderAPIKey","provider":"zhipu"}',
  name: 'EmbeddingError'
}
(node:27) Warning: Label '任务[1]: embeddings' already exists for console.time()
embeddingChunks error {
  message: '{"endpoint":"https://open.bigmodel.cn/api/paas/v4","error":{"status":401,"headers":{"connection":"keep-alive","content-length":"73","content-type":"application/json","date":"Fri, 17 Jan 2025 07:24:38 GMT","set-cookie":"acw_tc=784e2c9717370986788271365e5fd780e862d13092f08c8676826581724414;path=/;HttpOnly;Max-Age=1800","strict-transport-security":"max-age=31536000; includeSubDomains","vary":"Origin, Access-Control-Request-Method, Access-Control-Request-Headers","x-log-id":"20250117152438d5c069851eb24dc2"},"error":{"code":"401","message":"令牌已过期或验证不正确！"},"code":"401"},"errorType":"InvalidProviderAPIKey","provider":"zhipu"}',
  name: 'EmbeddingError'
}
(node:27) Warning: Label '任务[1]: embeddings' already exists for console.time()
embeddingChunks error {
  message: '{"endpoint":"https://open.bigmodel.cn/api/paas/v4","error":{"status":401,"headers":{"connection":"keep-alive","content-length":"73","content-type":"application/json","date":"Fri, 17 Jan 2025 07:24:41 GMT","set-cookie":"acw_tc=784e2c9717370986809661538e5fd7bbcfc705bafc2eb4d0d4378595d7c82e;path=/;HttpOnly;Max-Age=1800","strict-transport-security":"max-age=31536000; includeSubDomains","vary":"Origin, Access-Control-Request-Method, Access-Control-Request-Headers","x-log-id":"2025011715244170c13439180c40e3"},"error":{"code":"401","message":"令牌已过期或验证不正确！"},"code":"401"},"errorType":"InvalidProviderAPIKey","provider":"zhipu"}',
  name: 'EmbeddingError'
}
(node:27) Warning: Label '任务[1]: embeddings' already exists for console.time()`

**Comment by bunwen** [comment]
最上方是我常识切换不同的代理造成的

**Comment by cookieY** [comment]
@bunwen DEFAULT_FILES_CONFIG='embedding_model=zhipu/embedding-3'  把引号去掉 试试

**Comment by bunwen** [comment]
@cookieY 问题依旧

<img width="1773" alt="Image" src="https://github.com/user-attachments/assets/e1fc8c6a-6aad-44db-9f34-17fe4ccd6bf4" />

<img width="776" alt="Image" src="https://github.com/user-attachments/assets/ff84583d-5c89-43a0-8a96-24580a0f3ee6" />

<img width="891" alt="Image" src="https://github.com/user-attachments/assets/67262485-dbc1-47f3-a95e-79704b90750c" />

<img width="1027" alt="Image" src="https://github.com/user-attachments/assets/b6c745f4-13a3-4c7c-95f0-c412a94c8029" />

**Comment by cookieY** [comment]
使用的是 lobehub/lobe-chat-database:v1.46.7 这个镜像？

**Comment by bunwen** [comment]
> 使用的是 lobehub/lobe-chat-database:v1.46.7 这个镜像？

我发现日志里的时间不对劲。我看看是不是时区的问题

**Comment by bunwen** [comment]
``` yaml
name: lobe-chat-database
services:
  network-service:
    image: alpine
    container_name: lobe-network
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}' # MinIO API
      - '9001:9001' # MinIO Console
      - '${CASDOOR_PORT}:${CASDOOR_PORT}' # Casdoor
      - '${LOBE_PORT}:3210' # LobeChat
    command: tail -f /dev/null
    networks:
      - lobe-network

  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'SET_CONTAINER_TIMEZONE=true'
      - 'CONTAINER_TIMEZONE=Asia/Shanghai'
      - 'TZ=Asia/Shanghai'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: no
    networks:
      - lobe-network

  minio:
    image: minio/minio
    container_name: lobe-minio
    network_mode: 'service:network-service'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ROOT_USER}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=https://xxx.xxxx.xx'
      - 'SET_CONTAINER_TIMEZONE=true'
      - 'CONTAINER_TIMEZONE=Asia/Shanghai'
      - 'TZ=Asia/Shanghai'
    restart: no
    command: >
      server /etc/minio/data --address ":${MINIO_PORT}" --console-address ":9001"


  casdoor:
    image: casbin/casdoor:v1.788.0
    container_name: lobe-casdoor
    entrypoint: /bin/sh -c './server --createDatabase=true'
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      RUNNING_IN_DOCKER: 'true'
      driverName: 'postgres'
      dataSourceName: 'user=postgres password=${POSTGRES_PASSWORD} host=postgresql port=5432 sslmode=disable dbname=casdoor'
      origin: 'https://xxxxxxxx.xxxxx.xxx'
      runmode: 'dev'
      CONTAINER_TIMEZONE: 'Asia/Shanghai'
      SET_CONTAINER_TIMEZONE: true
      TZ: 'Asia/Shanghai'
    volumes:
      - ./init_data.json:/init_data.json

  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-chat
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
      network-service:
        condition: service_started
      minio:
        condition: service_started
      casdoor:
        condition: service_started

    environment:
      - 'APP_URL=https://xxxx.xxx.xx'
      - 'NEXT_AUTH_SSO_PROVIDERS=casdoor'
      - 'KEY_VAULTS_SECRET=xxxxxxx'
      - 'NEXT_AUTH_SECRET=xxxxxx'
      - 'AUTH_URL=https://xxxx.xxxx.xxxx/api/auth'
      - 'AUTH_CASDOOR_ISSUER=https://xxxxx.xxxx.xx'
      - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/${LOBE_DB_NAME}'
      - 'S3_ENDPOINT=https://xxxxx.xxxx.xxx'
      - 'S3_BUCKET=${MINIO_LOBE_BUCKET}'
      - 'S3_PUBLIC_DOMAIN=https://xxxxxxxx.xxx.xx'
      - 'S3_ENABLE_PATH_STYLE=1'
      - 'LLM_VISION_IMAGE_USE_BASE64=1'
      - 'SET_CONTAINER_TIMEZONE=true'
      - 'CONTAINER_TIMEZONE=Asia/Shanghai'
      - 'TZ=Asia/Shanghai'
    env_file:
      - .env
    restart: no

volumes:
  data:
    driver: local
  s3_data:
    driver: local

networks:
  lobe-network:
    driver: bridge

```
我不管是 单独设置TZ 还是 单独设置  CONTAINER_TIMEZONE、SET_CONTAINER_TIMEZONE 或者2者都设置 lobechat的console里一直都不生效
```
/ $ date
Fri Jan 17 08:29:58 Asia 2025
/ $ 
```

@cookieY 有啥好的建议吗
