### ISSUE TITLE
[Request] 请求添加自定义Embedding中 硅基流动/siliconflow 的选项

### ISSUE THREAD

**Issue by Guducat** [lobehub/lobe-chat#5645]
### 🥰 需求描述

请求添加自定义Embedding中 硅基流动/siliconflow 的选项
硅基流动有BAAI/bge-m3的嵌入模型，但是自定义Embedding不支持硅基流动，希望能支持一下

### 🧐 解决方案

提供适配

### 📝 补充信息

2025-04-03 此问题已解决
具体解决方案，在lobe的Docker-compose中引入如下片段：
```
 lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-chat
    [中间文字省略]
    environment:
      - 'SILICONCLOUD_API_KEY=YOUR-API-KEY'
      - 'DEFAULT_FILES_CONFIG=embedding_model=siliconcloud/BAAI/bge-m3'
      - 'SILICONCLOUD_PROXY_URL=https://api.siliconflow.cn/v1'
```
以上可以正常工作
