### ISSUE TITLE
[Bug] 使用环境变量配置了助手的默认模型，打开web页面后必须刷新一次才有效

### ISSUE THREAD

**Issue by hmzll** [lobehub/lobe-chat#5950]
### 📦 部署环境

Docker

### 📌 软件版本

1.52.9

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 当前环境
使用docker-compose部署

配置如下
```yaml
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - '3210:3210'
    environment:
      - 'DEFAULT_AGENT_CONFIG=model=deepseek-r1:latest;provider=ollama'
      - 'ENABLED_OPENAI=0'
      - 'OLLAMA_PROXY_URL=http://192.168.1.116:11434'
      - 'OLLAMA_MODEL_LIST=deepseek-r1:latest'
```

### 目前问题：
第一次打开页面时默认助手依然用的是：gpt-4o-mini，**必须刷新**一下才会变成`deepseek-r1:latest`

### 附加问题：
OLLAMA_PROXY_URL似乎未生效，在设置语言模型里，`Ollama服务地址`一栏依然为空，只显示了占位符没显示我环境变量里填的内网地址
