### ISSUE TITLE
[Bug] 设置了 DEFAULT_AGENT_CONFIG 后系统助手依然是 gpt-4o-mini

### ISSUE THREAD

**Issue by BrikerMan** [lobehub/lobe-chat#6014]
### 📦 Environment

Docker

### 📌 Version

v1.52.16

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

已经设置了 DEFAULT_AGENT_CONFIG，并且 ENABLED_OPENAI=0，但是 默认的系统助手依然使用 gpt-4o-mini

```yaml
version: '3.8'

services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - '3210:3210'
    env_file:
      - .env
```

```
DEFAULT_AGENT_CONFIG='model=deepseek-r1:32b;provider=ollama'
FEATURE_FLAGS="-knowledge_base"

ENABLED_OPENAI=0

ENABLED_OLLAMA=1
OLLAMA_PROXY_URL=http://192.168.2.206:11434
OLLAMA_MODEL_LIST="+deepseek-r1:32b,+qwen2.5:latest"
OLLAMA_ORIGINS="*"

LLM_VISION_IMAGE_USE_BASE64=1

```

### 📷 Recurrence Steps

- 使用 docker compose 启动 lobe chat
- 使用匿名浏览方式打开 lobechat 查看初始设置

### 🚦 Expected Behavior

希望可以把 agent 使用的模型替换掉
