### ISSUE TITLE
[Bug] 相同的版本，docker部署的就没有那么多服务商可以接入

### ISSUE THREAD

**Issue by catch6** [lobehub/lobe-chat#6255]
### 📦 部署环境

Docker

### 📦 部署模式

客户端模式(lobe-chat 镜像)

### 📌 软件版本

1.60.2

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

我使用Docker做私有化部署，部署的版本跟官方 https://chat-preview.lobehub.com/ 版本一致，都是1.60.2， 但是我的服务商里就没有那么多服务商可以接入，我目前主要使用火山引擎，但是我的里面没有

I use Docker for private deployment, and the deployed version is consistent with the official one at https://chat-preview.lobehub.com/, both being version 1.60.2. However, my service provider doesn't offer as many service integrations. Currently, I primarily use Volcano Engine, but it's not available in my setup.

### 📷 复现步骤

my docker-compose.yml
```yaml
services:
  lobechat:
    image: lobehub/lobe-chat:latest
    container_name: lobechat
    ports:
      - "3210:3210"
    restart: always
```
