### ISSUE TITLE
[Bug] [Help] 过一段时间之后容器会停止运行，求助如何打印详细日志

### ISSUE THREAD

**Issue by ChangeHow** [lobehub/lobe-chat#6292]
### 📦 部署环境

Docker

### 📦 部署模式

服务端模式(lobe-chat-database 镜像)

### 📌 软件版本

latest

### 💻 系统环境

Other Linux, Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

我在服务器上部署了 database 版本，最近频繁出现容器自动停止的情况；但是日志输出只有 info 级别的输出，不知道具体是什么问题导致的：

<img width="1039" alt="Image" src="https://github.com/user-attachments/assets/dd7aae2c-3bd4-4b2d-8640-04a52d4f1261" />

这个是我的  docker composer 配置：
```yaml
lobe:
    image: lobehub/lobe-chat-database:latest
    container_name: lobe-chat
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
      network-service:
        condition: service_started
      minio:
        condition: service_started

    environment:
      - 'APP_URL=https://****'
      # https://lobehub.com/zh/docs/self-hosting/environment-variables/auth
      - 'AUTH_URL=https://****/api/auth'
      - 'NEXTAUTH_URL=https://****'
      - 'NEXT_AUTH_SECRET=NX2ka********re5RfoT7hg'
      - 'NEXT_AUTH_SSO_PROVIDERS=generic-oidc' 
      - 'AUTH_GENERIC_OIDC_ID=67a********99231ea3a28'
      - 'AUTH_GENERIC_OIDC_SECRET=1a21bf********eaa712ee9ffa2e'
      - 'AUTH_GENERIC_OIDC_ISSUER=https://****authing.cn/oidc'
      - 'KEY_VAULTS_SECRET=Kix2wcUONd4CX51E********4wzJgKjPtz2sGztqQ='
      - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/${LOBE_DB_NAME}'
      - 'S3_ENDPOINT=http://127.0.0.1:${MINIO_PORT}'
      - 'S3_BUCKET=${MINIO_LOBE_BUCKET}'
      - 'S3_PUBLIC_DOMAIN=http://127.0.0.1:${MINIO_PORT}'
      - 'S3_ENABLE_PATH_STYLE=1'
      - 'LLM_VISION_IMAGE_USE_BASE64=1'
    env_file:
      - .env
    restart: on-failure:3

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    command: --interval 300 lobe-chat
    restart: always
    networks:
      - lobe-networ
```
可能是 watchover 重新拉取镜像导致自动重启失败的原因吗？

### 📷 复现步骤

暂无稳定复现步骤
