### ISSUE TITLE
[Bug] 不能一条一条的处理流式响应

### ISSUE THREAD

**Issue by jiongjiongJOJO** [lobehub/lobe-chat#6745]
### 📦 部署环境

Docker

### 📦 部署模式

服务端模式(lobe-chat-database 镜像)

### 📌 软件版本

v1.68.9

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

我本地开了一个openAI格式的API接口（在docker内），在lobechat里也设置了对应的接口。
我是使用docker-compose启动的，这里增加了一个API的容器，并把所有相关的服务放在了一起，所以lobechat只需要访问这个地址就能调用API接口：`http://api:port/v1`。
```
[user@localhost lobe-chat]#cat docker-compose.yml 
name: lobe-chat-database
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '*************:5432'
    volumes:
      - '*************:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=*************'
      - 'POSTGRES_PASSWORD=*************' # 需要替换为你的 PostgreSQL 数据库密码
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-database
    ports:
      - '*************:3210'
    depends_on:
      - postgresql
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:latest
    container_name: lobe-nginx
    ports:
      - "*************:80"
      - "*************:443"
    volumes:
      - *************:/etc/nginx/nginx.conf:ro
      - *************:/etc/nginx/ssl:ro
    depends_on:
      - lobe
    restart: always


  api:
    build: /root/API  # 直接指定 Dockerfile 目录
    container_name: API
    restart: unless-stopped

volumes:
  data:
    driver: local
```

然后配置好之后，可以直接使用这个api服务，但是这个服务的响应似乎不是一个字/Token一个字/Token的输出，从网络请求中可以看出，EventStream是一次性输出了多组信息，然后前端是一次性展示这些内容的。

但是我看api容器的日志，是实时输出的内容。并且我如果在我自己电脑运行这个api容器（不做其他的修改，完全一致），lobechat设置客户端请求的方式，来调用本机的接口（http://localhost:port/v1），是能正常输出Stream信息的。

这就很奇怪，我不确定是不是我docker的问题，但从现象上来看，不太可能是api容器的问题。

### 📷 复现步骤

这边录制了一个视频，可以直接从视频中查看现象：

https://github.com/user-attachments/assets/d9041247-f416-4736-8232-51b04916e575

### 🚦 期望结果

流式输出内容

### 📝 补充信息

暂无需要补充内容，如果有其他需要提供的内容，直接在这个issue内回复补充
