### ISSUE TITLE
[Bug] 无法发送图片（100%报错）

### ISSUE THREAD

**Issue by cyo57** [lobehub/lobe-chat#6755]
### 📦 Platform

Self hosting Docker

### 📦 Deploymenet mode

server db(lobe-chat-database image)

### 📌 Version

lobehub/lobe-chat-database:1.68.7

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

无法向任何发送图片，尝试过的有
- 硅基/Qwen2VL
- Gemini 2.0 Flash
- Gemini 2.0 Pro
- Doubao1.5-VisionPro

在聊天框内粘贴图片：

![Image](https://github.com/user-attachments/assets/62ca14df-637c-445e-8786-1aab642d91d6)

按下发送键后无法预览图片并且会报错，无法对话：
![Image](https://github.com/user-attachments/assets/1bb0957f-4372-4916-b0ce-4171327c0b15)

- Qwen2-VL
```json
{
  "error": {
    "status": 400,
    "headers": {
      "content-type": "application/json; charset=utf-8",
      "content-length": "128"
    }
  },
  "provider": "siliconcloud"
}
```

- Gemini 2.0 Flash
```json
{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://MYPROXY.MYPROXY/gemini/v1beta/models/gemini-2.0-flash-exp:streamGenerateContent?alt=sse: [400 Bad Request] Unable to submit request because it has a mimeType parameter with value application/xml, which is not supported. Update the mimeType and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini"
  },
  "provider": "google"
}
```

- Doubao 1.5 VisionPro
```json
{
  "error": {
    "code": "InvalidParameter",
    "type": "BadRequest",
    "param": "image_url",
    "message": "Invalid base64 image_url Request id: 02174125756537918eba5266a58c539c83c52fd7ffcXXXXXXXXX"
  },
  "endpoint": "https://ark.cn-beijing.volces.com/api/v3",
  "provider": "volcengine"
}
```

### 📷 Recurrence Steps

发送带图片的消息即报错！！

### 📝 Additional Information

使用官方一键部署脚本，Docker-compose.yaml
```yaml
root@hw-sh1:~/data/lobechat-db# cat docker-compose.yml 
name: lobe-chat-database
services:
  network-service:
    image: alpine
    container_name: lobe-network
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}' # MinIO API
      - '9001:9001' # MinIO Console
      - '${CASDOOR_PORT}:${CASDOOR_PORT}' # Casdoor
      - '${LOBE_PORT}:3210' # LobeChat
    command: tail -f /dev/null
    networks:
      - lobe-network

  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - lobe-network

  minio:
    image: minio/minio
    container_name: lobe-minio
    network_mode: 'service:network-service'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_API_CORS_ALLOW_ORIGIN=*'
    env_file:
      - .env
    restart: always
    entrypoint: >
      /bin/sh -c "
        minio server /etc/minio/data --address ':${MINIO_PORT}' --console-address ':9001' &
        MINIO_PID=\$!
        while ! curl -s http://localhost:${MINIO_PORT}/minio/health/live; do
          echo 'Waiting for MinIO to start...'
          sleep 1
        done
        sleep 5
        mc alias set myminio http://localhost:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
        echo 'Creating bucket ${MINIO_LOBE_BUCKET}'
        mc mb myminio/${MINIO_LOBE_BUCKET}
        wait \$MINIO_PID
      "

  casdoor:
    image: casbin/casdoor
    container_name: lobe-casdoor
    entrypoint: /bin/sh -c './server --createDatabase=true'
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      RUNNING_IN_DOCKER: 'true'
      driverName: 'postgres'
      dataSourceName: 'user=postgres password=${POSTGRES_PASSWORD} host=postgresql port=5432 sslmode=disable dbname=casdoor'
      runmode: 'dev'
    volumes:
      - ./init_data.json:/init_data.json
    env_file:
      - .env

  lobe:
    image: lobehub/lobe-chat-database:1.68.7
    container_name: lobe-chat
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
      network-service:
        condition: service_started
      minio:
        condition: service_started
      casdoor:
        condition: service_started

    environment:
      - 'NEXT_AUTH_SSO_PROVIDERS=casdoor'
      - 'KEY_VAULTS_SECRET=Kix2wcUONd4CX51E/ZPAd36BqM4wzJgKjPtz2sGztqQ='
      - 'NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg'
      - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/${LOBE_DB_NAME}'
      - 'S3_BUCKET=${MINIO_LOBE_BUCKET}'
      - 'S3_ENABLE_PATH_STYLE=1'
      - 'S3_ACCESS_KEY=${MINIO_ROOT_USER}'
      - 'S3_ACCESS_KEY_ID=${MINIO_ROOT_USER}'
      - 'S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}'
      - 'LLM_VISION_IMAGE_USE_BASE64=1'
    env_file:
      - .env
    restart: always

volumes:
  data:
    driver: local
  s3_data:
    driver: local

networks:
  lobe-network:
    driver: bridge
```

**Comment by NekokeCore** [comment]
有配置S3兼容的OSS或者自建过MinIO吗？

**Comment by cyo57** [comment]
> 有配置S3兼容的OSS或者自建过MinIO吗？

使用官方一键部署脚本，是MinIO，已更新issue

**Comment by NekokeCore** [comment]
> > 有配置S3兼容的OSS或者自建过MinIO吗？
> 
> 使用官方一键部署脚本，是MinIO，已更新issue

进minio后台看看存储桶是公开的还是私有的

**Comment by cyo57** [comment]
> > > 有配置S3兼容的OSS或者自建过MinIO吗？
> > 
> > 
> > 使用官方一键部署脚本，是MinIO，已更新issue
> 
> 进minio后台看看存储桶是公开的还是私有的

看起来确实是Minio出了问题，我这里无法访问Minio的webui。
看起来应该是我在部署的时候哪里搞错了

.env
```shell
MINIO_PORT=9000
APP_URL=https://lobe.XXX.top
AUTH_URL=https://lobe.XXX.top/api/auth

# MinIO S3 配置
MINIO_ROOT_USER=admin
MINIO_ROOT_PASSWORD=XXXXXX

# 在下方配置 minio 中添加的桶
S3_PUBLIC_DOMAIN=https://minio.XXX.top
S3_ENDPOINT=https://minio.XXX.top
MINIO_LOBE_BUCKET=lobe
```

docker-compose.yaml
```yaml
name: lobe-chat-database
services:
  network-service:
    image: alpine
    container_name: lobe-network
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}' # MinIO API
      - '9001:9001' # MinIO Console
      - '${CASDOOR_PORT}:${CASDOOR_PORT}' # Casdoor
      - '${LOBE_PORT}:3210' # LobeChat
    command: tail -f /dev/null
    networks:
      - lobe-network

  minio:
    image: minio/minio
    container_name: lobe-minio
    network_mode: 'service:network-service'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_API_CORS_ALLOW_ORIGIN=*'
    env_file:
      - .env
    restart: always
    entrypoint: >
      /bin/sh -c "
        minio server /etc/minio/data --address ':${MINIO_PORT}' --console-address ':9001' &
        MINIO_PID=\$!
        while ! curl -s http://localhost:${MINIO_PORT}/minio/health/live; do
          echo 'Waiting for MinIO to start...'
          sleep 1
        done
        sleep 5
        mc alias set myminio http://localhost:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
        echo 'Creating bucket ${MINIO_LOBE_BUCKET}'
        mc mb myminio/${MINIO_LOBE_BUCKET}
        wait \$MINIO_PID
      "

    environment:
      - 'NEXT_AUTH_SSO_PROVIDERS=casdoor'
      - 'KEY_VAULTS_SECRET=XXXXXX'
      - 'NEXT_AUTH_SECRET=XXXXXX'
      - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/${LOBE_DB_NAME}'
      - 'S3_BUCKET=${MINIO_LOBE_BUCKET}'
      - 'S3_ENABLE_PATH_STYLE=1'
      - 'S3_ACCESS_KEY=${MINIO_ROOT_USER}'
      - 'S3_ACCESS_KEY_ID=${MINIO_ROOT_USER}'
      - 'S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}'
      - 'LLM_VISION_IMAGE_USE_BASE64=1'
    env_file:
      - .env
    restart: always

volumes:
  data:
    driver: local
  s3_data:
    driver: local

networks:
  lobe-network:
    driver: bridge
```


重新部署：
```shell
root@hw-sh1:~/data/lobechat-db# docker-compose down; docker-compose up -d 
WARN[0000] The "MINIO_PID" variable is not set. Defaulting to a blank string. 
[+] Running 6/6
 ✔ Container lobe-chat                      Removed                                                                                                                                                                                                                   10.2s 
 ✔ Container lobe-casdoor                   Removed                                                                                                                                                                                                                    0.1s 
 ✔ Container lobe-minio                     Removed                                                                                                                                                                                                                   10.1s 
 ✔ Container lobe-postgres                  Removed                                                                                                                                                                                                                    0.2s 
 ✔ Container lobe-network                   Removed                                                                                                                                                                                                                   10.4s 
 ✔ Network lobe-chat-database_lobe-network  Removed                                                                                                                                                                                                                    0.2s 
WARN[0000] The "MINIO_PID" variable is not set. Defaulting to a blank string. 
[+] Running 6/6
 ✔ Network lobe-chat-database_lobe-network  Created                                                                                                                                                                                                                    0.1s 
 ✔ Container lobe-network                   Started                                                                                                                                                                                                                    0.1s 
 ✔ Container lobe-postgres                  Healthy                                                                                                                                                                                                                    0.1s 
 ✔ Container lobe-minio                     Started                                                                                                                                                                                                                    0.0s 
 ✔ Container lobe-casdoor                   Started                                                                                                                                                                                                                    0.0s 
 ✔ Container lobe-chat                      Started                                                                                                                                                                                                                    0.0s 
```

cat /etc/nginx/sites-enabled/lobe.XXX.top
```shell
server {
    listen 80;
    listen [::]:80;
    server_name lobe.XXX.top;
    return 301 https://$host$request_uri;
}

server {
...
    server_name lobe.XXX.top;
...
}

server {
...
    server_name auth.XXX.top;
...
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name minio.XXX.top;
    ssl_certificate /etc/nginx/ssl/*.XXX.top_XXX.top_2048/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/*.XXX.top_XXX.top_2048/private.key;
    location / {
        proxy_pass http://127.0.0.1:9000;  # 反向代理到本地9000端口
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # 设置允许的最大请求体大小
        client_max_body_size 256M;
    }
}
root@hw-sh1:~/data/lobechat-db#
```

通过curl访问Minio
```shell
root@hw-sh1:~/data/lobechat-db# curl https://minio.cloudyshore.top -i
HTTP/1.1 403 Forbidden
Server: nginx/1.18.0 (Ubuntu)
Date: Fri, 07 Mar 2025 13:38:56 GMT
Content-Type: application/xml
Content-Length: 254
Connection: keep-alive
Accept-Ranges: bytes
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
X-Amz-Request-Id: 182A88E80352F506
X-Content-Type-Options: nosniff
X-Ratelimit-Limit: 293
X-Ratelimit-Remaining: 293
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>182A88E80352F506</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>root@hw-sh1:~/data/lobechat-db#
```

如果通过浏览器访问Minio，URL会自动跳转到https://minio.XXX.top:9001/，无法正常打开，提示ERR_SSL_PROTOCOL_ERROR：

![Image](https://github.com/user-attachments/assets/86d2a98d-83fe-4811-bd02-b88bd2240d63)
