### ISSUE TITLE
Database migrate failed: There are records with NULL user_id values that could not be populated

### ISSUE THREAD

**Issue by GabrielxDuO** [lobehub/lobe-chat#7031]
### 📦 部署环境

Docker

### 📦 部署模式

服务端模式(lobe-chat-database 镜像)

### 📌 软件版本

1.72.0

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

watchtower 自动更新 lobe-chat-database 镜像至 1.72.0 并重启容器后数据库迁移失败。
回退版本至 1.71.5 后可正常运行。

### 📝 补充信息

日志：
```log
🌐 DNS Server: [ '127.0.0.11' ]
-------------------------------------
[Database] Start to migration...
❌ Database migrate failed. Please check your database is valid and DATABASE_URL is set correctly. The error detail is below:
error: There are records with NULL user_id values that could not be populated
    at /app/node_modules/.pnpm/pg@8.14.1/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /app/node_modules/drizzle-orm/pg-core/dialect.cjs:66:13
    at async NodePgSession.transaction (/app/node_modules/drizzle-orm/node-postgres/session.cjs:177:22)
    at async PgDialect.migrate (/app/node_modules/drizzle-orm/pg-core/dialect.cjs:62:5)
    at async Object.migrate (/app/node_modules/drizzle-orm/node-postgres/migrator.cjs:27:3)
    at async runMigrations (/app/docker.cjs:17:3) {
  length: 186,
  severity: 'ERROR',
  code: 'P0001',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'PL/pgSQL function inline_code_block line 31 at RAISE',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'pl_exec.c',
  line: '3911',
  routine: 'exec_stmt_raise'
}
❌ Error during DB migration:
Error: 🔴 Process exited with code 1
    at ChildProcess.<anonymous> (/app/startServer.js:109:39)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

compose.yml:
```yaml
name: lobe-chat-database
services:
  lobe-chat:
    image: lobehub/lobe-chat-database
    container_name: lobe-chat
    restart: always
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    ports:
      - '127.0.0.1:<REDACTED_PORT>:3210'
    environment:
      - 'APP_URL=https://<REDACTED_DOMAIN>'
      - 'KEY_VAULTS_SECRET=<REDACTED_SECRET>'
      - 'DATABASE_DRIVER=node'
      - 'DATABASE_URL=postgresql://<REDACTED_USER>:<REDACTED_PASSWORD>@lobe-chat-pgvector/lobe'
      - 'NEXT_AUTH_SECRET=<REDACTED_SECRET>'
      - 'NEXT_AUTH_SSO_PROVIDERS=github'
      - 'NEXTAUTH_URL=https://<REDACTED_DOMAIN>/api/auth'
      - 'AUTH_GITHUB_ID=<REDACTED_GITHUB_ID>'
      - 'AUTH_GITHUB_SECRET=<REDACTED_GITHUB_SECRET>'
      - 'S3_ENDPOINT=https://<REDACTED_S3_ENDPOINT>'
      - 'S3_BUCKET=lobe'
      - 'S3_ACCESS_KEY_ID=<REDACTED_S3_ACCESS_KEY>'
      - 'S3_SECRET_ACCESS_KEY=<REDACTED_S3_SECRET_KEY>'
      - 'S3_SET_ACL=0'
      - 'S3_PUBLIC_DOMAIN=https://<REDACTED_S3_PUBLIC_DOMAIN>'
      - 'S3_ENABLE_PATH_STYLE=0'
      - 'LLM_VISION_IMAGE_USE_BASE64=1'
      - 'SEARXNG_URL=http://searxng:8080'
    depends_on:
      - pgvector

  pgvector:
    image: pgvector/pgvector:pg16
    container_name: lobe-chat-pgvector
    environment:
      - 'POSTGRES_DB=lobe'
      - 'POSTGRES_PASSWORD=<REDACTED_POSTGRES_PASSWORD>'
    expose:
      - 5432
    volumes:
      - './data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  searxng:
    image: searxng/searxng
    container_name: lobe-chat-searxng
    restart: always
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    volumes:
      - './searxng-settings.yml:/etc/searxng/settings.yml'
    environment:
      - 'SEARXNG_SETTINGS_FILE=/etc/searxng/settings.yml'
```
