### ISSUE TITLE
[Request]  提供 docker-compose 文件，方便部署 

### ISSUE THREAD

**Issue by luojiyin1987** [lobehub/lobe-chat#722]
### 🥰 需求描述 | Feature Description

提供 docker-compose 文件，方便部署。 docker run 不好管理

### 🧐 解决方案 | Proposed Solution

```yml
version: '3.3'
services:
    lobe-chat:
        ports:
            - '13210:3210'
        environment:
            - OPENAI_API_KEY=sk-xxxxx   # 填写你的API KEY
            - ACCESS_CODE=123456    # 填一个密码，不然你的额度很快就会被刷完
            - OPENAI_PROXY_URL=http://openai.api/v1

        image: lobehub/lobe-chat
        container_name: lobe-chat
        restart: always
```
用户跟踪自己的情况修改 OPENAI_API_KEY，OPENAI_PROXY_URL和 ports。
在配置 OPENAI_PROXY_URL 不要忘记后面的 `v1` 。 
目前对外使用的端口是 13210，根据用户情况修改。  
 `restart: always`   使 docker 容器，开机自启动，当运行出问题的时候，尝试重启。
