### ISSUE TITLE
[Question] URL 携带 /chat 路径，Edge 浏览器刷新会报错

### ISSUE THREAD

**Issue by rtpacks** [lobehub/lobe-chat#761]
### 🧐 问题描述 | Proposed Solution

**问题：** URL 携带 /chat 路径，Edge 浏览器刷新会报错，在 Chrome 和 Firefox 中同样的操作不会触发这个错误

![image](https://github.com/lobehub/lobe-chat/assets/97966585/8218a82f-a7a6-4fee-a65e-1fbd8561b80c)

**复现步骤：**
1. 使用 docker-compose 部署
2. 访问部署地址，URL出现 /chat#session=inbox 后刷新 Edge 浏览器，出现上面错误
3. 移除 URL 的 /chat#session=inbox，页面路由重定向正常

### 📝 补充信息 | Additional Information

**部署方式：docker compose 部署**
```yaml
version: '3' 

services:
  lobe:
    image: lobehub/lobe-chat
    container_name: lobe
    restart: always
    # volumes:
      # - ./data:/data
    # network_mode: "host"
    ports:
      - 7007:3210
    environment:
      OPENAI_API_KEY: sk-xx
      OPENAI_PROXY_URL: https://api.gptapi.us/v1
      ACCESS_CODE: xxx
```

**版本信息**
Microsoft Edge
版本 120.0.2210.77 (正式版本) (64 位)

Firefox
版本 121.0  (64 位)

Google Chrome
版本 120.0.6099.110（正式版本） （64 位）
