### ISSUE TITLE
[Bug] PLUGINS_INDEX_URL 环境变量设置不生效

### ISSUE THREAD

**Issue by deepwzh** [lobehub/lobe-chat#792]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

docker设置PLUGINS_INDEX_URL 变量后不生效，AGENTS_INDEX_URL是生效的

### 🚦 期望结果 | Expected Behavior

设置变量后，能使用本地的插件索引

### 📷 复现步骤 | Recurrence Steps

docker-compose 配置
```
version: '3'
services:
  lobe-chat:
    image: lobehub/lobe-chat
    ports:
    - "3210:3210"
    environment:
    - OPENAI_API_KEY=sk-bzQ1HmijnBHtVvod369d5026Bb014fEc94B33e32F6C6Bc00
    - OPENAI_PROXY_URL=http://192.168.1.131:3500/v1
    - ACCESS_CODE=
    - AGENTS_INDEX_URL=https://xxxx/chatgpt-index/agents-index
    - PLUGINS_INDEX_URL=https://xxxx/chatgpt-index/plugins-index
    restart: always
```
