### ISSUE TITLE
【开启推理强度调整】设置为关闭的状态下，似乎依旧生效

### ISSUE THREAD

**Issue by xxddff** [lobehub/lobe-chat#8177]
### 📦 部署环境

Docker

### 📦 部署模式

服务端模式(lobe-chat-database 镜像)

### 📌 软件版本

1.94.7

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Safari

### 🐛 问题描述

更新到1.94.0之后 #8110 问题解决了，可以在模型设置中看到【开启推理强度调整】，但是一旦开启了这个设置，并设置为”中“以外的选项，之后在设置中关闭该选项，切换非推理模型就会报错
```yaml
{
  "error": {
    "code": null,
    "type": "invalid_request_error",
    "param": null,
    "message": "Unrecognized request argument supplied: reasoning_effort"
  },
  "endpoint": "********************",
  "provider": "openai"
}
```
测试过1.94.0和1.94.7都会报错
退回[1.88.20](https://github.com/lobehub/lobe-chat/releases/tag/v1.88.20)，也就是pr #7998 的上一个版本，设置【开启推理强度调整】是正常的，不会出现关闭该设置的情况下调用非推理模型报错

### 📷 复现步骤

在随便聊聊/新建助手中开启【开启推理强度调整】并设置为“高”，关闭【开启推理强度调整】，切换到非推理模型进行对话

### 🚦 期望结果

【开启推理强度调整】可以被正确关闭

### 📝 补充信息

可能和 #8065 类似
去数据库里手动删掉reasoning_effort就正常了，但是总不能每次要关闭该设置就手动去数据库里删吧
看了一下数据库，仅打开【开启推理强度调整】设置并不会写入reasoning_effort，但是调整为“高”之后就会写入
